'use strict';

// ESLint v9 flat config (lives at the repo root — paths below are relative
// to that location).
// Two distinct contexts coexist in this repo:
//   1. Node.js code (app/server/**, app/index.js, tools/build/**,
//      tools/dev-server/**, tools/tests/**)
//      → modern CJS, runs in Node 20 inside Node-for-Max for app/server,
//        and in plain Node.js for tools/.
//   2. Max [js] code (app/lom_router.js)
//      → SpiderMonkey ES5, no Node, exposed globals are LiveAPI/Dict/Task/etc.
// They need different parser settings and different rule sets.

const js = require('@eslint/js');
const globals = require('globals');
const jsdoc = require('eslint-plugin-jsdoc');

// Shared JSDoc rule overrides — the `flat/recommended` preset is too prescriptive
// out of the box (forces @file / @example / sentence-shaped descriptions). We
// keep its structural checks (types valid, param names match, tags well-formed)
// and turn off the prose policing.
const jsdocRuleOverrides = {
  'jsdoc/require-file-overview': 'off',
  'jsdoc/require-example': 'off',
  'jsdoc/match-description': 'off',
  'jsdoc/require-description-complete-sentence': 'off',
  // require-jsdoc is now `error` — every top-level function declaration must
  // carry JSDoc. The codebase was fully covered by the JSDoc rollout (commits
  // 075b501, 95205e4, 0e01df8 + this one). Tests still opt-out via their own
  // config block.
  'jsdoc/require-jsdoc': [
    'error',
    {
      require: {
        FunctionDeclaration: true,
        MethodDefinition: false,
        ClassDeclaration: false,
        // Don't force JSDoc on inline arrow functions / one-liner const
        // assignments — ~50 small helpers in tools/*.js would all be noise.
        ArrowFunctionExpression: false,
        FunctionExpression: false,
      },
    },
  ],
  // These are too noisy in practice — leaving descriptions optional.
  'jsdoc/require-param-description': 'off',
  'jsdoc/require-returns-description': 'off',
  // `unknown` and `any` are perfectly fine type values for our context
  // (no TS, no full type system).
  'jsdoc/no-undefined-types': 'off',
  // Respect the existing house style — blank line between description and @tags
  // is common and improves readability in long JSDoc blocks.
  'jsdoc/tag-lines': 'off',
};

module.exports = [
  {
    ignores: [
      'node_modules/**',
      '**/node_modules/**',
      'dist/**',
      'coverage/**',
      '.idea/**',
      '.vscode/**',
      '**/*.amxd',
      // Generated by tools/build/concat-lom.js — sources are app/lom_router/*.
      'app/lom_router.js',
    ],
  },

  // Default rules — Node CJS code
  {
    files: [
      'app/server/**/*.js',
      'app/index.js',
      'tools/build/**/*.js',
      'tools/dev-server/**/*.js',
    ],
    plugins: { jsdoc },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        ...globals.node,
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      ...jsdoc.configs['flat/recommended'].rules,
      ...jsdocRuleOverrides,
      'no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      'no-console': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },

  // Special: app/lom_router/*.js runs in Max [js] (modern SpiderMonkey + LiveAPI
  // globals). `lom_*` functions are entry points invoked by Max via outlet
  // messages — not imported from JS code, so they look "unused" to ESLint.
  // Mark them as such. Cross-file references inside app/lom_router/ are also
  // expected — the build concatenates them into one file, so helpers defined
  // in 00_helpers.js are visible from every other file at runtime.
  // ecmaVersion is 2022 because the runtime is Max 9's SpiderMonkey, which is
  // far past ES5 (the codebase uses trailing commas in args, shorthand object
  // syntax, etc.). Convention is still "no arrow funcs / no class / use var"
  // for stylistic consistency, but eslint doesn't enforce that — runtime does.
  {
    files: ['app/lom_router/**/*.js'],
    plugins: { jsdoc },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        // Max [js] globals
        LiveAPI: 'readonly',
        Dict: 'readonly',
        Task: 'readonly',
        outlet: 'readonly',
        post: 'readonly',
        error: 'readonly',
        messnamed: 'readonly',
        inlets: 'writable',
        outlets: 'writable',
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      ...jsdoc.configs['flat/recommended'].rules,
      ...jsdocRuleOverrides,
      'no-var': 'off',
      'prefer-const': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
      // Cross-file references are the whole point of the build-time concat —
      // a helper defined in 00_helpers.js is consumed everywhere. Linting each
      // source file in isolation can't see this, so we disable no-undef.
      // (Real undefined-variable bugs would still surface at runtime.)
      'no-undef': 'off',
      'no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^(_|lom_)',
          caughtErrorsIgnorePattern: '^(_|e$)',
        },
      ],
    },
  },

  // Tests: co-located *.test.js files. Skip require-jsdoc entirely (test
  // names already describe intent) and inject Jest globals (describe / it /
  // expect / beforeEach / etc.) so eslint doesn't flag them as undefined.
  // Placed AFTER the lom_router block so it wins for app/lom_router/*.test.js
  // (flat config: last matching block's languageOptions take precedence).
  {
    files: ['**/*.test.js'],
    plugins: { jsdoc },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: {
        ...globals.node,
        ...globals.jest,
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      ...jsdoc.configs['flat/recommended'].rules,
      ...jsdocRuleOverrides,
      // Tests don't carry JSDoc on their internal helpers — test names
      // describe intent and helper signatures are obvious in context.
      'jsdoc/require-jsdoc': 'off',
      'jsdoc/require-returns': 'off',
      'jsdoc/require-param': 'off',
      'jsdoc/require-param-type': 'off',
      'no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
      ],
      'no-console': 'off',
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
];
