// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Helpers shared across domains: id resolution, child iteration, path
// construction, return-value normalization. All `_xxx` private helpers.

/**
 * Run `fn()` and outlet its return value as `lom_response id ok value`.
 * Any thrown Error becomes `lom_response id error message`. Absorbs the
 * try/catch boilerplate that every handler used to repeat, and lets
 * handlers signal user-facing errors with `throw new Error(msg)` instead
 * of an inline `outlet(0, 'lom_response', id, 'error', msg); return`.
 *
 * @param {number} id - Request id for the response envelope.
 * @param {() => unknown} fn - Body of the handler. Whatever it returns is
 *   the success payload (use 'done' for void operations).
 */
function _handle(id, fn) {
  try {
    outlet(0, 'lom_response', id, 'ok', fn());
  } catch (e) {
    outlet(0, 'lom_response', id, 'error', e.message);
  }
}

/**
 * Build a clip path from track+slot indices.
 *
 * @param {number} t
 * @param {number} s
 * @returns {string}
 */
function _clipPath(t, s) {
  return 'live_set tracks ' + parseInt(t) + ' clip_slots ' + parseInt(s) + ' clip';
}

/**
 * Build a clip-slot path from track+slot indices.
 *
 * @param {number} t
 * @param {number} s
 * @returns {string}
 */
function _slotPath(t, s) {
  return 'live_set tracks ' + parseInt(t) + ' clip_slots ' + parseInt(s);
}

/**
 * Build a track path from a track index.
 *
 * @param {number} t
 * @returns {string}
 */
function _trackPath(t) {
  return 'live_set tracks ' + parseInt(t);
}

/**
 * Build a device path from track + device index.
 *
 * @param {number} t
 * @param {number} d
 * @returns {string}
 */
function _devicePath(t, d) {
  return 'live_set tracks ' + parseInt(t) + ' devices ' + parseInt(d);
}

/**
 * Normalize a Live notes-API return value to a JSON string. Live 12+ returns
 * JSON directly; older versions returned a Dict name we have to fetch.
 *
 * @param {string|Array} raw - Either a JSON string starting with '{' or a Dict name (or array thereof).
 * @returns {string}
 */
function _dictReturnToJson(raw) {
  if (typeof raw === 'string' && raw.charAt(0) === '{') {
    return raw;
  }
  var dictName = Array.isArray(raw) ? raw[raw.length - 1] : raw;
  return new Dict(dictName).stringify();
}

/**
 * Map an io_type token to its corresponding child-list property name on a
 * Device. Returns null for unknown tokens.
 *
 * @param {string} ioType - 'audio_in' | 'audio_out' | 'midi_in' | 'midi_out'.
 * @returns {string|null}
 */
function _ioListProp(ioType) {
  return (
    {
      audio_in: 'audio_inputs',
      audio_out: 'audio_outputs',
      midi_in: 'midi_inputs',
      midi_out: 'midi_outputs',
    }[String(ioType)] || null
  );
}

/**
 * Build a LiveAPI from a numeric id. Returns null if the id is missing or
 * zero (LOM convention for "not present").
 *
 * @param {number|string} idValue
 * @returns {object|null}
 */
function _byId(idValue) {
  if (!idValue || idValue === 0 || idValue === '0') return null;
  return new LiveAPI(null, 'id', idValue);
}

/**
 * Resolve a single child's LiveAPI id by its index in the parent's child
 * list. Returns 0 if out of range — matches LOM's "not present" sentinel.
 *
 * @param {object} parent
 * @param {string} childKey
 * @param {number} index
 * @returns {number}
 */
function _resolveChildId(parent, childKey, index) {
  var ids = parent.get(childKey) || [];
  var pos = parseInt(index) * 2;
  if (pos + 1 >= ids.length || ids[pos] !== 'id') return 0;
  return ids[pos + 1];
}

/**
 * Iterate a parent's child list and call `fn(api, index)` for each child.
 * Returning false from fn breaks early. Children whose id is 0 are skipped.
 *
 * @param {object} parent
 * @param {string} childKey
 * @param {(api: object, index: number) => unknown} fn
 */
function _foreachChild(parent, childKey, fn) {
  var ids = parent.get(childKey) || [];
  for (var i = 0; i < ids.length; i += 2) {
    var api = _byId(ids[i + 1]);
    if (!api) continue;
    if (fn(api, i / 2) === false) break;
  }
}

/**
 * Specialized for CuePoint resolution. Kept as a thin wrapper because every
 * cue_point setter/method calls it.
 *
 * @param {number} cueIndex
 * @returns {number}
 */
function _resolveCueId(cueIndex) {
  var song = new LiveAPI(null, 'live_set');
  return _resolveChildId(song, 'cue_points', cueIndex);
}

/**
 * If `v` is an array, return its last element ; otherwise return it as-is.
 * Many LiveAPI getters return a single-element array — this normalizes them.
 *
 * @param {unknown} v
 * @returns {unknown}
 */
function _unwrap(v) {
  return Array.isArray(v) ? v[v.length - 1] : v;
}

/**
 * Path of a rack-class device on a track.
 *
 * @param {number} track
 * @param {number} devIdx
 * @returns {string}
 */
function _rackPath(track, devIdx) {
  return 'live_set tracks ' + parseInt(track) + ' devices ' + parseInt(devIdx);
}

/**
 * Path of a Chain inside a regular Rack.
 *
 * @param {number} track
 * @param {number} devIdx
 * @param {number} chainIdx
 * @returns {string}
 */
function _chainPath(track, devIdx, chainIdx) {
  return _rackPath(track, devIdx) + ' chains ' + parseInt(chainIdx);
}

/**
 * Path of a DrumPad inside a Drum Rack. padIdx is the canonical drum_pads
 * index (= MIDI note 0..127).
 *
 * @param {number} track
 * @param {number} devIdx
 * @param {number} padIdx
 * @returns {string}
 */
function _drumPadPath(track, devIdx, padIdx) {
  return _rackPath(track, devIdx) + ' drum_pads ' + parseInt(padIdx);
}

// CJS export — only fires when this file is `require`d by a test runner.
// In Max [js] (the actual runtime) `module` is undefined and the assignment
// is skipped, leaving the top-level `function` declarations as the only
// exposure (which is what Max needs anyway). The `else` branch is
// unreachable from Jest, so we tell Istanbul to ignore it.
/* istanbul ignore else */
if (typeof module !== 'undefined') {
  module.exports = {
    _handle,
    _clipPath,
    _slotPath,
    _trackPath,
    _devicePath,
    _dictReturnToJson,
    _ioListProp,
    _byId,
    _resolveChildId,
    _foreachChild,
    _resolveCueId,
    _unwrap,
    _rackPath,
    _chainPath,
    _drumPadPath,
  };
}
