// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Dispatcher entry points: generic lom_request (get/set/call any LOM path),
// peer scan, full session state snapshot.

/**
 * Generic LOM dispatcher: get / set / call against any LOM path. Args layout
 * is (id, op, nParts, ...pathParts, prop, ...extras). Outlets `lom_response
 * id ok value` or `lom_response id error message`.
 */
function lom_request() {
  var args = Array.prototype.slice.call(arguments);
  var id = args[0];
  var op = args[1];
  var nParts = parseInt(args[2]);
  var pathParts = args.slice(3, 3 + nParts);
  var lomPath = pathParts.join(' ');
  var prop = args[3 + nParts];
  // 'get' has no extras; 'set' has 1 (the value); 'call' has 0..N (method args)
  var extras = args.slice(3 + nParts + 1);

  _handle(id, function () {
    var api = new LiveAPI(null, lomPath);
    if (op === 'get') return _unwrap(api.get(prop));
    if (op === 'set') {
      api.set(prop, extras[0]);
      return 'done';
    }
    if (op === 'call') {
      var result = extras.length > 0 ? api.call.apply(api, [prop].concat(extras)) : api.call(prop);
      return result !== undefined ? result : 'done';
    }
    throw new Error('unsupported op: ' + op);
  });
}

/**
 * Scan LiveSet (tracks + return_tracks + master) for agent4live peer devices.
 * Marker = a `live.numbox` named `__agent4live_marker__` that every device
 * carries. Outlets JSON `{selfId, peers: [{deviceId, trackName, position, isSelf}, ...]}`.
 *
 * @param {number} id
 */
function lom_scan_peers(id) {
  _handle(id, function () {
    var selfApi = new LiveAPI(null, 'this_device');
    var selfId = selfApi.id;

    var MARKER_NAME = '__agent4live_marker__';
    var peers = [];

    /**
     * @param {object} track
     * @param {string} trackName
     */
    function scanDevicesOnTrack(track, trackName) {
      var pos = 0;
      _foreachChild(track, 'devices', function (device) {
        var devId = device.id;
        _foreachChild(device, 'parameters', function (param) {
          if (String(param.get('name')) === MARKER_NAME) {
            peers.push({
              deviceId: devId,
              trackName: trackName,
              position: pos,
              isSelf: devId == selfId,
            });
            return false; // stop param scan, marker found
          }
        });
        pos++;
      });
    }

    var liveSet = new LiveAPI(null, 'live_set');
    _foreachChild(liveSet, 'tracks', function (trackApi) {
      scanDevicesOnTrack(trackApi, String(trackApi.get('name')));
    });
    _foreachChild(liveSet, 'return_tracks', function (returnApi) {
      scanDevicesOnTrack(returnApi, String(returnApi.get('name')));
    });

    var masterApi = new LiveAPI(null, 'live_set master_track');
    scanDevicesOnTrack(masterApi, String(masterApi.get('name')));

    return JSON.stringify({ selfId: selfId, peers: peers });
  });
}

/**
 * Full session snapshot: tempo, is_playing, list of tracks (index, name,
 * is_midi_track, muted), list of scenes (index, name).
 *
 * @param {number} id
 */
function lom_session_state(id) {
  _handle(id, function () {
    var song = new LiveAPI(null, 'live_set');

    var tracks = [];
    _foreachChild(song, 'tracks', function (track, index) {
      tracks.push({
        index: index,
        name: String(track.get('name')),
        is_midi_track: Boolean(parseInt(_unwrap(track.get('is_midi_track')))),
        muted: Boolean(parseInt(_unwrap(track.get('mute')))),
      });
    });

    var scenes = [];
    _foreachChild(song, 'scenes', function (scene, index) {
      scenes.push({
        index: index,
        name: String(scene.get('name')),
      });
    });

    return JSON.stringify({
      tempo: _unwrap(song.get('tempo')),
      is_playing: Boolean(_unwrap(song.get('is_playing'))),
      track_count: tracks.length,
      scene_count: scenes.length,
      tracks: tracks,
      scenes: scenes,
    });
  });
}

// CJS export — only fires when this file is `require`d by a test runner.
// In Max [js] (the actual runtime) `module` is undefined and the assignment
// is skipped, leaving the top-level `function` declarations as the only
// exposure (which is what Max needs anyway). The `else` branch is
// unreachable from Jest, so we tell Istanbul to ignore it.
/* istanbul ignore else */
if (typeof module !== 'undefined') {
  module.exports = {
    lom_request,
    lom_scan_peers,
    lom_session_state,
  };
}
