// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Clip operations: notes (read/add/replace/modify/remove/duplicate),
// warp markers, audio info, envelope clearing, arrangement-clip lifecycle,
// session-clip duplication, groove assignment.

/**
 * Read notes inside a region of a clip (Live 11+ get_notes_extended).
 * Outlets the result Dict serialized as JSON.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} fromPitch
 * @param {number} pitchSpan
 * @param {number} fromTime
 * @param {number} timeSpan
 */
function lom_get_clip_notes(id, trackIndex, slotIndex, fromPitch, pitchSpan, fromTime, timeSpan) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var raw = clip.call(
      'get_notes_extended',
      parseInt(fromPitch),
      parseInt(pitchSpan),
      parseFloat(fromTime),
      parseFloat(timeSpan),
    );
    return _dictReturnToJson(raw);
  });
}

/**
 * Wipe every note in the clip and lay down a new set (atomic). notesJson
 * shape matches lom_add_clip's notes param.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} notesJson - JSON array of {pitch,time,duration,velocity?,mute?}.
 */
function lom_replace_clip_notes(id, trackIndex, slotIndex, notesJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var clipLength = parseFloat(clip.get('length'));

    // Wipe everything in the clip's full pitch and time range.
    clip.call('remove_notes_extended', 0, 128, 0, clipLength);

    var notes = JSON.parse(String(notesJson));
    if (notes.length > 0) {
      var spec = { notes: [] };
      for (var i = 0; i < notes.length; i++) {
        var n = notes[i];
        spec.notes.push({
          pitch: parseInt(n.pitch),
          start_time: parseFloat(n.time),
          duration: parseFloat(n.duration),
          velocity: parseInt(n.velocity || 100),
          mute: parseInt(n.mute || 0),
        });
      }
      var d = new Dict();
      d.parse(JSON.stringify(spec));
      clip.call('add_new_notes', d);
    }

    return 'done';
  });
}

/**
 * Modify existing notes by note_id (Live 11+). Only listed properties change;
 * notes not in clip are silently ignored.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} notesJson - { notes: [{ note_id, ...changes }, ...] } as JSON.
 */
function lom_apply_note_modifications(id, trackIndex, slotIndex, notesJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var d = new Dict();
    d.parse(String(notesJson));
    clip.call('apply_note_modifications', d);
    return 'done';
  });
}

/**
 * Outlet JSON of all notes in a clip (Live 11+ get_all_notes_extended).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 */
function lom_get_all_notes(id, trackIndex, slotIndex) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    return _dictReturnToJson(clip.call('get_all_notes_extended'));
  });
}

/**
 * Outlet JSON of the currently selected notes in a clip
 * (Live 11+ get_selected_notes_extended).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 */
function lom_get_selected_notes(id, trackIndex, slotIndex) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    return _dictReturnToJson(clip.call('get_selected_notes_extended'));
  });
}

/**
 * Outlet JSON of specific notes by note_id. Live's get_notes_by_id accepts
 * a varargs list of atom note IDs, which we splat from the JSON array.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} idsJson - JSON array of note_id integers.
 */
function lom_get_notes_by_id(id, trackIndex, slotIndex, idsJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var ids = JSON.parse(String(idsJson));
    return _dictReturnToJson(clip.call.apply(clip, ['get_notes_by_id'].concat(ids)));
  });
}

/**
 * Add a warp marker on an audio clip. At least one of beat_time / sample_time
 * must be provided; the other is sent as NaN to mean "omit".
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} beatTime - NaN means "omit".
 * @param {number} sampleTime - NaN means "omit".
 */
function lom_add_warp_marker(id, trackIndex, slotIndex, beatTime, sampleTime) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var spec = {};
    var bt = parseFloat(beatTime);
    var st = parseFloat(sampleTime);
    if (!isNaN(bt)) spec.beat_time = bt;
    if (!isNaN(st)) spec.sample_time = st;
    if (Object.keys(spec).length === 0) {
      throw new Error('add_warp_marker: at least one of beat_time / sample_time required');
    }
    var d = new Dict();
    d.parse(JSON.stringify(spec));
    clip.call('add_warp_marker', d);
    return 'done';
  });
}

/**
 * Create a new MIDI clip in a session slot and optionally seed it with notes.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} clipLength - In beats.
 * @param {string} notesJson - JSON array of {pitch,time,duration,velocity?,mute?} (may be []).
 */
function lom_add_clip(id, trackIndex, slotIndex, clipLength, notesJson) {
  _handle(id, function () {
    var notes = JSON.parse(String(notesJson));
    var slotPath = _slotPath(trackIndex, slotIndex);
    var slot = new LiveAPI(null, slotPath);
    slot.call('create_clip', parseFloat(clipLength));

    if (notes.length > 0) {
      var clip = new LiveAPI(null, slotPath + ' clip');
      var spec = { notes: [] };
      for (var i = 0; i < notes.length; i++) {
        var n = notes[i];
        spec.notes.push({
          pitch: parseInt(n.pitch),
          start_time: parseFloat(n.time),
          duration: parseFloat(n.duration),
          velocity: parseInt(n.velocity || 100),
          mute: parseInt(n.mute || 0),
        });
      }
      var d = new Dict();
      d.parse(JSON.stringify(spec));
      clip.call('add_new_notes', d);
    }

    return 'done';
  });
}

/**
 * Clear automation envelope for ONE specific DeviceParameter on a clip.
 * Resolves the param via path (track / device / parameter index), then
 * passes its id to clip.clear_envelope.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} deviceIndex
 * @param {number} paramIndex
 */
function lom_clear_clip_envelope(id, trackIndex, slotIndex, deviceIndex, paramIndex) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var paramPath = _devicePath(trackIndex, deviceIndex) + ' parameters ' + parseInt(paramIndex);
    var p = new LiveAPI(null, paramPath);
    var pid = p.id;
    if (!pid || pid === 0 || pid === '0') throw new Error('No parameter at ' + paramPath);
    clip.call('clear_envelope', 'id', pid);
    return 'done';
  });
}

/**
 * Track.duplicate_clip_to_arrangement(clip, destination_time). The clip param
 * is a LiveAPI clip ID, so we resolve it from track+slot first.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} destTime
 */
function lom_duplicate_clip_to_arrangement(id, trackIndex, slotIndex, destTime) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var clipId = clip.id;
    if (!clipId || clipId === 0 || clipId === '0') {
      throw new Error('No clip at track ' + trackIndex + ', slot ' + slotIndex);
    }
    var track = new LiveAPI(null, _trackPath(trackIndex));
    track.call('duplicate_clip_to_arrangement', 'id', clipId, parseFloat(destTime));
    return 'done';
  });
}

/**
 * Track.delete_clip(clip) — for arrangement clips. Resolves clip id from
 * track.arrangement_clips[N], then calls Track.delete_clip with that id.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} arrClipIndex
 */
function lom_delete_arrangement_clip(id, trackIndex, arrClipIndex) {
  _handle(id, function () {
    var track = new LiveAPI(null, _trackPath(trackIndex));
    var clips = track.get('arrangement_clips') || [];
    // arrangement_clips comes back as alternating ['id', N] pairs.
    var idx = parseInt(arrClipIndex);
    var pos = idx * 2;
    if (pos + 1 >= clips.length || clips[pos] !== 'id') {
      throw new Error('Arrangement clip index ' + idx + ' out of range');
    }
    track.call('delete_clip', 'id', clips[pos + 1]);
    return 'done';
  });
}

/**
 * Remove notes by ID (Live 11+). Variadic atoms call.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} idsJson - JSON array of note_id integers.
 */
function lom_remove_notes_by_id(id, trackIndex, slotIndex, idsJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var ids = JSON.parse(String(idsJson));
    if (!Array.isArray(ids) || ids.length === 0) return 'no-op';
    clip.call.apply(clip, ['remove_notes_by_id'].concat(ids));
    return 'done';
  });
}

/**
 * Duplicate notes by ID (Live 11+). Uses the dict form for optional
 * destination_time + transposition_amount support.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} paramsJson - { note_ids, destination_time?, transposition_amount? }.
 */
function lom_duplicate_notes_by_id(id, trackIndex, slotIndex, paramsJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var p = JSON.parse(String(paramsJson));
    var spec = { note_ids: p.note_ids };
    if (p.destination_time !== undefined && p.destination_time !== null)
      spec.destination_time = p.destination_time;
    if (p.transposition_amount !== undefined && p.transposition_amount !== null)
      spec.transposition_amount = p.transposition_amount;
    var d = new Dict();
    d.parse(JSON.stringify(spec));
    clip.call('duplicate_notes_by_id', d);
    return 'done';
  });
}

/**
 * Add notes to an EXISTING clip (vs replace_clip_notes which wipes first).
 * Outlets list of note IDs of the added notes (Live 11+) as JSON.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} notesJson - JSON array (may be empty).
 */
function lom_add_notes_to_clip(id, trackIndex, slotIndex, notesJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var notes = JSON.parse(String(notesJson));
    if (!Array.isArray(notes) || notes.length === 0) return '[]';
    var spec = { notes: [] };
    for (var i = 0; i < notes.length; i++) {
      var n = notes[i];
      var entry = {
        pitch: parseInt(n.pitch),
        start_time: parseFloat(n.start_time !== undefined ? n.start_time : n.time),
        duration: parseFloat(n.duration),
        velocity: parseFloat(n.velocity !== undefined ? n.velocity : 100),
      };
      if (n.mute !== undefined) entry.mute = parseInt(n.mute);
      if (n.probability !== undefined) entry.probability = parseFloat(n.probability);
      if (n.velocity_deviation !== undefined)
        entry.velocity_deviation = parseFloat(n.velocity_deviation);
      if (n.release_velocity !== undefined) entry.release_velocity = parseFloat(n.release_velocity);
      spec.notes.push(entry);
    }
    var d = new Dict();
    d.parse(JSON.stringify(spec));
    var raw = clip.call('add_new_notes', d);
    // add_new_notes returns the list of note IDs of added notes.
    var ids = Array.isArray(raw) ? raw : raw ? [raw] : [];
    return JSON.stringify(ids);
  });
}

/**
 * Duplicate a session clip to another slot. Resolves target clip_slot ref
 * from track + slot indices, then ClipSlot.duplicate_clip_to(target_slot).
 *
 * @param {number} id
 * @param {number} srcTrack
 * @param {number} srcSlot
 * @param {number} dstTrack
 * @param {number} dstSlot
 */
function lom_duplicate_clip_to_slot(id, srcTrack, srcSlot, dstTrack, dstSlot) {
  _handle(id, function () {
    var src = new LiveAPI(null, _slotPath(srcTrack, srcSlot));
    var dstPath = _slotPath(dstTrack, dstSlot);
    var dst = new LiveAPI(null, dstPath);
    var dstId = dst.id;
    if (!dstId || dstId === 0 || dstId === '0') throw new Error('No clip slot at ' + dstPath);
    src.call('duplicate_clip_to', 'id', dstId);
    return 'done';
  });
}

/**
 * Assign a groove to a clip (or clear it if grooveIndex < 0). Clip.groove is
 * a child-ref prop set via clip.set('groove', 'id', N).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} grooveIndex - Negative means "clear".
 */
function lom_set_clip_groove(id, trackIndex, slotIndex, grooveIndex) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    if (parseInt(grooveIndex) < 0) {
      clip.set('groove', 'id', 0);
      return 'cleared';
    }
    var g = new LiveAPI(null, 'live_set groove_pool grooves ' + parseInt(grooveIndex));
    var gid = g.id;
    if (!gid || gid === 0 || gid === '0') throw new Error('No groove at index ' + grooveIndex);
    clip.set('groove', 'id', gid);
    return 'done';
  });
}

/**
 * Read all audio-clip-relevant props in one round-trip. Falls back gracefully
 * for MIDI clips where audio props don't exist (returns is_audio_clip=false).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 */
function lom_get_clip_audio_info(id, trackIndex, slotIndex) {
  _handle(id, function () {
    var c = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var isAudio = Boolean(parseInt(_unwrap(c.get('is_audio_clip'))));
    var info = { is_audio_clip: isAudio };
    if (isAudio) {
      info.file_path = String(_unwrap(c.get('file_path')) || '');
      info.sample_length = parseInt(_unwrap(c.get('sample_length')));
      info.sample_rate = parseFloat(_unwrap(c.get('sample_rate')));
      info.warping = Boolean(parseInt(_unwrap(c.get('warping'))));
      info.warp_mode = parseInt(_unwrap(c.get('warp_mode')));
      info.gain = parseFloat(_unwrap(c.get('gain')));
      info.pitch_coarse = parseInt(_unwrap(c.get('pitch_coarse')));
      info.pitch_fine = parseFloat(_unwrap(c.get('pitch_fine')));
      info.start_marker = parseFloat(_unwrap(c.get('start_marker')));
      info.end_marker = parseFloat(_unwrap(c.get('end_marker')));
      info.ram_mode = Boolean(parseInt(_unwrap(c.get('ram_mode'))));
    }
    return JSON.stringify(info);
  });
}

/**
 * Read warp markers of an audio clip. Clip.warp_markers returns a Dict with
 * pairs of sample_time / beat_time. Same Live 12 vs 11 envelope situation
 * as the note Dict ops — use _dictReturnToJson.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 */
function lom_get_warp_markers(id, trackIndex, slotIndex) {
  _handle(id, function () {
    var c = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var raw = c.get('warp_markers');
    var val = Array.isArray(raw) && raw.length === 1 ? raw[0] : raw;
    if (typeof val === 'string' && val.charAt(0) === '{') {
      // Live 12+: JSON string envelope. Unwrap the {warp_markers: ...} key.
      try {
        var parsed = JSON.parse(val);
        return JSON.stringify(parsed.warp_markers !== undefined ? parsed.warp_markers : parsed);
      } catch (_) {}
    }
    // Fallback: try the Dict-name pattern (older Live).
    return _dictReturnToJson(raw);
  });
}

// CJS export — only fires when this file is `require`d by a test runner.
// In Max [js] (the actual runtime) `module` is undefined and the assignment
// is skipped, leaving the top-level `function` declarations as the only
// exposure (which is what Max needs anyway). The `else` branch is
// unreachable from Jest, so we tell Istanbul to ignore it.
/* istanbul ignore else */
if (typeof module !== 'undefined') {
  module.exports = {
    lom_get_clip_notes,
    lom_replace_clip_notes,
    lom_apply_note_modifications,
    lom_get_all_notes,
    lom_get_selected_notes,
    lom_get_notes_by_id,
    lom_add_warp_marker,
    lom_add_clip,
    lom_clear_clip_envelope,
    lom_duplicate_clip_to_arrangement,
    lom_delete_arrangement_clip,
    lom_remove_notes_by_id,
    lom_duplicate_notes_by_id,
    lom_add_notes_to_clip,
    lom_duplicate_clip_to_slot,
    lom_set_clip_groove,
    lom_get_clip_audio_info,
    lom_get_warp_markers,
  };
}
