// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Device operations: device list, parameter list, move device, IO routings
// for Max-for-Live and plugin devices.

/**
 * Unwrap a LiveAPI dict-typed property: Live 12+ returns a JSON-string
 * envelope `{"<prop>": value}` ; older Live returns alternating key/value
 * lists or single-element arrays. Returns the inner value.
 *
 * @param {object} api
 * @param {string} propName
 * @returns {unknown}
 */
function _unwrapDictProp(api, propName) {
  var raw = api.get(propName);
  var val = Array.isArray(raw) && raw.length === 1 ? raw[0] : raw;
  if (typeof val === 'string' && val.charAt(0) === '{') {
    try {
      var parsed = JSON.parse(val);
      return parsed[propName] !== undefined ? parsed[propName] : parsed;
    } catch (_) {}
  }
  if (Array.isArray(val)) {
    var o = {};
    for (var i = 0; i < val.length; i += 2) o[val[i]] = val[i + 1];
    return o;
  }
  return val;
}

/**
 * Outlet JSON of a device's IO routings (audio / midi, in / out). Each
 * DeviceIO entry has its current routing_type, routing_channel, plus the
 * available_* lists for those props.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} deviceIndex
 */
function lom_get_device_io_routings(id, trackIndex, deviceIndex) {
  _handle(id, function () {
    var devPath = _devicePath(trackIndex, deviceIndex);
    var dev = new LiveAPI(null, devPath);
    /**
     * @param {string} listProp
     * @returns {Array|null}
     */
    function readIoList(listProp) {
      var count = 0;
      try {
        count = parseInt(dev.getcount(listProp));
      } catch (_) {
        return null;
      }
      if (!count) return [];
      var out = [];
      for (var i = 0; i < count; i++) {
        var io = new LiveAPI(null, devPath + ' ' + listProp + ' ' + i);
        out.push({
          index: i,
          routing_type: _unwrapDictProp(io, 'routing_type'),
          routing_channel: _unwrapDictProp(io, 'routing_channel'),
          available_types: _unwrapDictProp(io, 'available_routing_types'),
          available_channels: _unwrapDictProp(io, 'available_routing_channels'),
        });
      }
      return out;
    }
    return JSON.stringify({
      audio_inputs: readIoList('audio_inputs'),
      audio_outputs: readIoList('audio_outputs'),
      midi_inputs: readIoList('midi_inputs'),
      midi_outputs: readIoList('midi_outputs'),
    });
  });
}

/**
 * Set a Dict-typed property (routing_type or routing_channel) on a DeviceIO.
 * Validates against the device's available_<prop>s list and preserves the
 * native identifier type (Live 12 returns ints for some channels, symbols
 * for others — Dict round-trip must keep that type).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} deviceIndex
 * @param {string} ioType - 'audio_in' | 'audio_out' | 'midi_in' | 'midi_out'.
 * @param {number} ioIndex
 * @param {string} propName - 'routing_type' or 'routing_channel'.
 * @param {string} identifier
 */
function _setDeviceIoDictProp(id, trackIndex, deviceIndex, ioType, ioIndex, propName, identifier) {
  _handle(id, function () {
    var listProp = _ioListProp(ioType);
    if (!listProp) throw new Error('invalid io_type: ' + ioType);
    var ioPath = _devicePath(trackIndex, deviceIndex) + ' ' + listProp + ' ' + parseInt(ioIndex);
    var io = new LiveAPI(null, ioPath);
    var availName = 'available_' + propName + 's';
    var rawAvail = io.get(availName);
    var availStr = Array.isArray(rawAvail) && rawAvail.length === 1 ? rawAvail[0] : rawAvail;
    var avail = [];
    if (typeof availStr === 'string' && availStr.charAt(0) === '{') {
      try {
        var parsed = JSON.parse(availStr);
        avail = parsed[availName] || [];
      } catch (_) {}
    }
    var idStr = String(identifier);
    var match = null;
    for (var i = 0; i < avail.length; i++) {
      if (String(avail[i].identifier) === idStr) {
        match = avail[i];
        break;
      }
    }
    if (!match) {
      var have = [];
      for (var j = 0; j < avail.length; j++) {
        have.push(JSON.stringify(avail[j].identifier) + ' (' + avail[j].display_name + ')');
      }
      throw new Error(
        'No ' + propName + ' with identifier "' + idStr + '". Available: ' + have.join(', ')
      );
    }
    var d = new Dict();
    d.parse(JSON.stringify(match));
    io.set(propName, d);
    return JSON.stringify(match);
  });
}

/**
 * @param {number} id
 * @param {number} t
 * @param {number} d
 * @param {string} ioType
 * @param {number} ioIdx
 * @param {string} identifier
 */
function lom_set_device_io_routing_type(id, t, d, ioType, ioIdx, identifier) {
  _setDeviceIoDictProp(id, t, d, ioType, ioIdx, 'routing_type', identifier);
}

/**
 * @param {number} id
 * @param {number} t
 * @param {number} d
 * @param {string} ioType
 * @param {number} ioIdx
 * @param {string} identifier
 */
function lom_set_device_io_routing_channel(id, t, d, ioType, ioIdx, identifier) {
  _setDeviceIoDictProp(id, t, d, ioType, ioIdx, 'routing_channel', identifier);
}

/**
 * Outlet JSON `[{index, name, class_name}, ...]` for every device on a track.
 * Uses getcount('devices') to dodge the "empty track returns ['id', 0]"
 * sentinel and addresses each device by canonical path (more robust to
 * dangling LiveAPI IDs).
 *
 * @param {number} id
 * @param {number} trackIndex
 */
function lom_get_track_devices(id, trackIndex) {
  _handle(id, function () {
    var trackPath = _trackPath(trackIndex);
    var track = new LiveAPI(null, trackPath);
    var count = parseInt(track.getcount('devices'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var dev = new LiveAPI(null, trackPath + ' devices ' + i);
      out.push({
        index: i,
        name: String(_unwrap(dev.get('name'))),
        class_name: String(_unwrap(dev.get('class_name'))),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON `[{index, name, value, min, max, is_quantized, is_enabled,
 * value_items?}, ...]` for every DeviceParameter on a device. value_items
 * (the discrete labels) is included only for quantized params.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} deviceIndex
 */
function lom_get_device_params(id, trackIndex, deviceIndex) {
  _handle(id, function () {
    var devPath = _devicePath(trackIndex, deviceIndex);
    var dev = new LiveAPI(null, devPath);
    var count = parseInt(dev.getcount('parameters'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var p = new LiveAPI(null, devPath + ' parameters ' + i);
      var entry = {
        index: i,
        name: String(_unwrap(p.get('name'))),
        value: parseFloat(_unwrap(p.get('value'))),
        min: parseFloat(_unwrap(p.get('min'))),
        max: parseFloat(_unwrap(p.get('max'))),
        is_quantized: Boolean(parseInt(_unwrap(p.get('is_quantized')))),
        is_enabled: Boolean(parseInt(_unwrap(p.get('is_enabled')))),
      };
      if (entry.is_quantized) {
        var items = p.get('value_items');
        if (Array.isArray(items)) {
          entry.value_items = items.map(function (x) {
            return String(x);
          });
        }
      }
      out.push(entry);
    }
    return JSON.stringify(out);
  });
}

/**
 * Move a device from a source track/index to a target track at a given
 * position. Song.move_device(device, target_track, target_position).
 *
 * @param {number} id
 * @param {number} fromTrack
 * @param {number} fromIdx
 * @param {number} toTrack
 * @param {number} toPosition
 */
function lom_move_device(id, fromTrack, fromIdx, toTrack, toPosition) {
  _handle(id, function () {
    var srcPath = _devicePath(fromTrack, fromIdx);
    var src = new LiveAPI(null, srcPath);
    var srcId = src.id;
    if (!srcId || srcId === 0 || srcId === '0') throw new Error('No device at ' + srcPath);
    var dstPath = _trackPath(toTrack);
    var dst = new LiveAPI(null, dstPath);
    var dstId = dst.id;
    if (!dstId || dstId === 0 || dstId === '0') throw new Error('No track at ' + dstPath);
    var song = new LiveAPI(null, 'live_set');
    song.call('move_device', 'id', srcId, 'id', dstId, parseInt(toPosition));
    return 'done';
  });
}

// CJS export — only fires when this file is `require`d by a test runner.
// In Max [js] (the actual runtime) `module` is undefined and the assignment
// is skipped, leaving the top-level `function` declarations as the only
// exposure (which is what Max needs anyway). The `else` branch is
// unreachable from Jest, so we tell Istanbul to ignore it.
/* istanbul ignore else */
if (typeof module !== 'undefined') {
  module.exports = {
    _unwrapDictProp,
    lom_get_device_io_routings,
    _setDeviceIoDictProp,
    lom_set_device_io_routing_type,
    lom_set_device_io_routing_channel,
    lom_get_track_devices,
    lom_get_device_params,
    lom_move_device,
  };
}
