// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Rack devices: chain listing, drum pad listing, chain/pad device drilldown,
// macros (read / add / remove / randomize), rack variations, drum-chain props.

/**
 * Read chain props (regular Rack chain or DrumPad chain — same Chain class).
 *
 * @param {string} chainPath
 * @param {number} chainIdx
 * @returns {object}
 */
function _readChain(chainPath, chainIdx) {
  var c = new LiveAPI(null, chainPath);
  return {
    chain_idx: chainIdx,
    name: String(_unwrap(c.get('name')) || ''),
    color: parseInt(_unwrap(c.get('color'))),
    mute: Boolean(parseInt(_unwrap(c.get('mute')))),
    solo: Boolean(parseInt(_unwrap(c.get('solo')))),
    muted_via_solo: Boolean(parseInt(_unwrap(c.get('muted_via_solo')))),
    has_audio_input: Boolean(parseInt(_unwrap(c.get('has_audio_input')))),
    has_audio_output: Boolean(parseInt(_unwrap(c.get('has_audio_output')))),
    has_midi_input: Boolean(parseInt(_unwrap(c.get('has_midi_input')))),
    has_midi_output: Boolean(parseInt(_unwrap(c.get('has_midi_output')))),
  };
}

/**
 * Outlet JSON list of chains in a regular Rack (Audio Effect Rack, Instrument
 * Rack). Returns [] for Drum Racks (use lom_get_drum_pads instead) or
 * non-rack devices.
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_get_rack_chains(id, track, devIdx) {
  _handle(id, function () {
    var rack = new LiveAPI(null, _rackPath(track, devIdx));
    var count = parseInt(rack.getcount('chains'));
    var out = [];
    for (var i = 0; i < count; i++) {
      out.push(_readChain(_chainPath(track, devIdx, i), i));
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON list of drum pads in a Drum Rack. With `onlyVisible=1`, returns
 * only the 16 pads visible in the matrix view ; otherwise the full 0..127 list.
 * Each entry: { pad_idx, name, note, mute, solo, chain_count } (pad_idx is
 * always the canonical drum_pads index = MIDI note, regardless of mode).
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} onlyVisible - 1 to filter to visible_drum_pads.
 */
function lom_get_drum_pads(id, track, devIdx, onlyVisible) {
  _handle(id, function () {
    var rackPath = _rackPath(track, devIdx);
    var rack = new LiveAPI(null, rackPath);
    var listProp = parseInt(onlyVisible) === 1 ? 'visible_drum_pads' : 'drum_pads';
    var count = parseInt(rack.getcount(listProp));
    var out = [];
    for (var i = 0; i < count; i++) {
      var padPath =
        parseInt(onlyVisible) === 1
          ? rackPath + ' visible_drum_pads ' + i
          : _drumPadPath(track, devIdx, i);
      var p = new LiveAPI(null, padPath);
      var note = parseInt(_unwrap(p.get('note')));
      if (isNaN(note) || note < 0) continue;
      out.push({
        pad_idx: note,
        name: String(_unwrap(p.get('name')) || ''),
        note: note,
        mute: Boolean(parseInt(_unwrap(p.get('mute')))),
        solo: Boolean(parseInt(_unwrap(p.get('solo')))),
        chain_count: parseInt(p.getcount('chains')),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON list of devices inside a regular Rack chain at depth 1.
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} chainIdx
 */
function lom_get_chain_devices(id, track, devIdx, chainIdx) {
  _handle(id, function () {
    var chainPath = _chainPath(track, devIdx, chainIdx);
    var chain = new LiveAPI(null, chainPath);
    var count = parseInt(chain.getcount('devices'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var d = new LiveAPI(null, chainPath + ' devices ' + i);
      out.push({
        index: i,
        name: String(_unwrap(d.get('name')) || ''),
        class_name: String(_unwrap(d.get('class_name')) || ''),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON list of chains nested inside a DrumPad. DrumPad chains are
 * DrumChain instances (Chain props + in_note / out_note / choke_group).
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} padIdx
 */
function lom_get_drum_pad_chains(id, track, devIdx, padIdx) {
  _handle(id, function () {
    var padPath = _drumPadPath(track, devIdx, padIdx);
    var pad = new LiveAPI(null, padPath);
    var count = parseInt(pad.getcount('chains'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var c = new LiveAPI(null, padPath + ' chains ' + i);
      out.push({
        chain_idx: i,
        name: String(_unwrap(c.get('name')) || ''),
        mute: Boolean(parseInt(_unwrap(c.get('mute')))),
        solo: Boolean(parseInt(_unwrap(c.get('solo')))),
        in_note: parseInt(_unwrap(c.get('in_note'))),
        out_note: parseInt(_unwrap(c.get('out_note'))),
        choke_group: parseInt(_unwrap(c.get('choke_group'))),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON list of devices inside a DrumPad's chain (1 level deeper than
 * lom_get_chain_devices).
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} padIdx
 * @param {number} chainIdx
 */
function lom_get_drum_pad_chain_devices(id, track, devIdx, padIdx, chainIdx) {
  _handle(id, function () {
    var chainPath = _drumPadPath(track, devIdx, padIdx) + ' chains ' + parseInt(chainIdx);
    var chain = new LiveAPI(null, chainPath);
    var count = parseInt(chain.getcount('devices'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var d = new LiveAPI(null, chainPath + ' devices ' + i);
      out.push({
        index: i,
        name: String(_unwrap(d.get('name')) || ''),
        class_name: String(_unwrap(d.get('class_name')) || ''),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Generic device-params reader at any path — shared by chain & drum-pad-chain
 * param tools (logic mirrors lom_get_device_params).
 *
 * @param {string} devPath
 * @returns {Array}
 */
function _readDeviceParams(devPath) {
  var dev = new LiveAPI(null, devPath);
  var count = parseInt(dev.getcount('parameters'));
  var out = [];
  for (var i = 0; i < count; i++) {
    var p = new LiveAPI(null, devPath + ' parameters ' + i);
    var entry = {
      index: i,
      name: String(_unwrap(p.get('name'))),
      value: parseFloat(_unwrap(p.get('value'))),
      min: parseFloat(_unwrap(p.get('min'))),
      max: parseFloat(_unwrap(p.get('max'))),
      is_quantized: Boolean(parseInt(_unwrap(p.get('is_quantized')))),
      is_enabled: Boolean(parseInt(_unwrap(p.get('is_enabled')))),
    };
    if (entry.is_quantized) {
      var items = p.get('value_items');
      if (Array.isArray(items))
        entry.value_items = items.map(function (x) {
          return String(x);
        });
    }
    out.push(entry);
  }
  return out;
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} chainIdx
 * @param {number} subDevIdx
 */
function lom_get_chain_device_params(id, track, devIdx, chainIdx, subDevIdx) {
  _handle(id, function () {
    var devPath = _chainPath(track, devIdx, chainIdx) + ' devices ' + parseInt(subDevIdx);
    return JSON.stringify(_readDeviceParams(devPath));
  });
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} padIdx
 * @param {number} chainIdx
 * @param {number} subDevIdx
 */
function lom_get_drum_pad_chain_device_params(id, track, devIdx, padIdx, chainIdx, subDevIdx) {
  _handle(id, function () {
    var devPath =
      _drumPadPath(track, devIdx, padIdx) +
      ' chains ' +
      parseInt(chainIdx) +
      ' devices ' +
      parseInt(subDevIdx);
    return JSON.stringify(_readDeviceParams(devPath));
  });
}

/**
 * Outlet JSON of a rack's macros + variation state in one call. Macros are
 * filtered by name prefix `Macro ` (parameters[0] is usually device on/off).
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_get_rack_macros(id, track, devIdx) {
  _handle(id, function () {
    var rackPath = _rackPath(track, devIdx);
    var rack = new LiveAPI(null, rackPath);
    var paramCount = parseInt(rack.getcount('parameters'));
    var macros = [];
    for (var i = 0; i < paramCount; i++) {
      var p = new LiveAPI(null, rackPath + ' parameters ' + i);
      var name = String(_unwrap(p.get('name')) || '');
      if (name.indexOf('Macro ') === 0) {
        macros.push({
          index: i,
          name: name,
          value: parseFloat(_unwrap(p.get('value'))),
          min: parseFloat(_unwrap(p.get('min'))),
          max: parseFloat(_unwrap(p.get('max'))),
        });
      }
    }
    return JSON.stringify({
      visible_macro_count: parseInt(_unwrap(rack.get('visible_macro_count'))),
      variation_count: parseInt(_unwrap(rack.get('variation_count'))),
      selected_variation_index: parseInt(_unwrap(rack.get('selected_variation_index'))),
      has_macro_mappings: Boolean(parseInt(_unwrap(rack.get('has_macro_mappings')))),
      macros: macros,
    });
  });
}

/**
 * Generic call wrapper for the simple rack/variation actions. Kept here
 * (rather than reusing lom_call) to avoid round-tripping through lom_request
 * and to keep semantics tied to a track+device addressing.
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {string} methodName
 */
function _rackCall(id, track, devIdx, methodName) {
  _handle(id, function () {
    var rack = new LiveAPI(null, _rackPath(track, devIdx));
    rack.call(methodName);
    return 'done';
  });
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_add_rack_macro(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'add_macro');
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_remove_rack_macro(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'remove_macro');
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_randomize_rack_macros(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'randomize_macros');
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_store_rack_variation(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'store_variation');
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_recall_last_used_variation(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'recall_last_used_variation');
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_delete_rack_variation(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'delete_selected_variation');
}

/**
 * Recall a specific variation by index. Sets selected_variation_index then
 * calls recall_selected_variation. -1 means "current selection, no change".
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} variationIdx
 */
function lom_recall_rack_variation(id, track, devIdx, variationIdx) {
  _handle(id, function () {
    var rack = new LiveAPI(null, _rackPath(track, devIdx));
    var idx = parseInt(variationIdx);
    if (idx >= 0) rack.set('selected_variation_index', idx);
    rack.call('recall_selected_variation');
    return 'done';
  });
}

/**
 * Insert a new (empty) chain in a regular Rack at the given position
 * (Live 12.3+). Throws if insertion is impossible (Drum Rack restrictions etc).
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} position - Negative or NaN means "at end".
 */
function lom_insert_rack_chain(id, track, devIdx, position) {
  _handle(id, function () {
    var rack = new LiveAPI(null, _rackPath(track, devIdx));
    var pos = parseInt(position);
    if (pos < 0 || isNaN(pos)) rack.call('insert_chain');
    else rack.call('insert_chain', pos);
    return 'done';
  });
}

/**
 * Drum Rack: copy the entire content of a pad to another pad slot.
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} sourceIdx
 * @param {number} destIdx
 */
function lom_copy_drum_pad(id, track, devIdx, sourceIdx, destIdx) {
  _handle(id, function () {
    var rack = new LiveAPI(null, _rackPath(track, devIdx));
    rack.call('copy_pad', parseInt(sourceIdx), parseInt(destIdx));
    return 'done';
  });
}

/**
 * Bundle: set in_note, out_note, choke_group on a DrumChain. -999 (or NaN)
 * skips a field. in_note = -1 means "All Notes" in the UI; choke_group = 0
 * = none.
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} padIdx
 * @param {number} chainIdx
 * @param {number} inNote
 * @param {number} outNote
 * @param {number} chokeGroup
 */
function lom_set_drum_chain_props(
  id,
  track,
  devIdx,
  padIdx,
  chainIdx,
  inNote,
  outNote,
  chokeGroup,
) {
  _handle(id, function () {
    var c = new LiveAPI(
      null,
      _drumPadPath(track, devIdx, padIdx) + ' chains ' + parseInt(chainIdx),
    );
    var n;
    n = parseInt(inNote);
    if (!isNaN(n) && n !== -999) c.set('in_note', n);
    n = parseInt(outNote);
    if (!isNaN(n) && n !== -999) c.set('out_note', n);
    n = parseInt(chokeGroup);
    if (!isNaN(n) && n !== -999) c.set('choke_group', n);
    return 'done';
  });
}

// CJS export — only fires when this file is `require`d by a test runner.
// In Max [js] (the actual runtime) `module` is undefined and the assignment
// is skipped, leaving the top-level `function` declarations as the only
// exposure (which is what Max needs anyway). The `else` branch is
// unreachable from Jest, so we tell Istanbul to ignore it.
/* istanbul ignore else */
if (typeof module !== 'undefined') {
  module.exports = {
    _readChain,
    lom_get_rack_chains,
    lom_get_drum_pads,
    lom_get_chain_devices,
    lom_get_drum_pad_chains,
    lom_get_drum_pad_chain_devices,
    _readDeviceParams,
    lom_get_chain_device_params,
    lom_get_drum_pad_chain_device_params,
    lom_get_rack_macros,
    _rackCall,
    lom_add_rack_macro,
    lom_remove_rack_macro,
    lom_randomize_rack_macros,
    lom_store_rack_variation,
    lom_recall_last_used_variation,
    lom_delete_rack_variation,
    lom_recall_rack_variation,
    lom_insert_rack_chain,
    lom_copy_drum_pad,
    lom_set_drum_chain_props,
  };
}
