// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Push notifications via LiveAPI observers. Each observe call returns an
// observer id; the bridge outlets `lom_event obsId value` on every change
// (with throttle + trailing flush).
//
// Per-observer state. Keyed by an integer id we hand out at lom_observe time
// and the bridge can use to address the observer (lom_unobserve + matching
// lom_event back to the right URI). Each entry holds:
//   api          : the LiveAPI instance with .property = <prop> + callback
//   throttle_ms  : minimum gap between two emitted events (0 = no throttle)
//   last_emit    : timestamp of last emission
//   pending      : the most recent suppressed value waiting to be flushed
//   timer_id     : Max Task scheduling the trailing flush, null if none
var observers = {}; // id -> { api, throttle_ms, last_emit, pending, timer_id, prop }
var nextObsId = 1;

/**
 * Trailing-edge throttle: when an event arrives too fast and is suppressed,
 * we schedule a Task that flushes the most recent value once the throttle
 * window has passed. Guarantees we never lose the *final* value of a burst
 * (e.g. tempo settles at 130 after 60 frames of dragging — agent must see
 * 130, not the last value before throttle kicked in).
 *
 * @param {number} obsId
 */
function _scheduleObserverFlush(obsId) {
  var st = observers[obsId];
  if (!st || st.timer_id !== null) return;
  var delay = Math.max(0, st.throttle_ms - (Date.now() - st.last_emit));
  st.timer_id = new Task(function () {
    var s = observers[obsId];
    if (!s) return;
    s.timer_id = null;
    if (s.pending === null) return;
    s.last_emit = Date.now();
    var val = s.pending;
    s.pending = null;
    outlet(0, 'lom_event', obsId, _serializeForOutlet(val));
  });
  st.timer_id.schedule(delay);
}

/**
 * Coerce a value into something Max-outlet-friendly. Numbers / bools / strings
 * pass through ; lists and dicts are JSON-stringified so Node-side consumers
 * can decode uniformly.
 *
 * @param {unknown} val
 * @returns {string|number|boolean}
 */
function _serializeForOutlet(val) {
  if (val === undefined || val === null) return '';
  if (typeof val === 'number' || typeof val === 'boolean' || typeof val === 'string') return val;
  try {
    return JSON.stringify(val);
  } catch (e) {
    return String(val);
  }
}

/**
 * Subscribe to a LiveAPI property. Hands back an integer observer id (in the
 * `lom_response` envelope) that the bridge uses to address the observer for
 * unobserve and to route incoming `lom_event obsId value` notifications.
 *
 * @param {number} id
 * @param {string} lomPath
 * @param {string} prop
 * @param {number} throttleMs - 0 = no throttle.
 */
function lom_observe(id, lomPath, prop, throttleMs) {
  _handle(id, function () {
    var path = String(lomPath);
    var propName = String(prop);
    var throttle = Math.max(0, parseInt(throttleMs) || 0);
    var obsId = nextObsId++;

    var handler = function (args) {
      // args = [<prop_name>, value_or_values_flat]. Single-atom case keeps a
      // scalar ; multi-atom (dict-typed props returning key/value pairs)
      // forwards the original structure.
      var st = observers[obsId];
      if (!st) return; // stale callback after free
      var raw = args.slice(1);
      var val = raw.length === 1 ? raw[0] : raw;

      var now = Date.now();
      if (throttle === 0 || now - st.last_emit >= throttle) {
        st.last_emit = now;
        st.pending = null;
        outlet(0, 'lom_event', obsId, _serializeForOutlet(val));
      } else {
        // Suppressed by throttle — remember the latest value and schedule a
        // trailing flush so the final value of a burst is never lost.
        st.pending = val;
        _scheduleObserverFlush(obsId);
      }
    };

    var api = new LiveAPI(handler, path);
    api.property = propName;

    observers[obsId] = {
      api: api,
      throttle_ms: throttle,
      last_emit: 0,
      pending: null,
      timer_id: null,
      prop: propName,
    };

    return obsId;
  });
}

/**
 * Stop a previously-registered observer. Idempotent: unobserving an
 * already-freed observer outlets `ok already-freed`.
 *
 * @param {number} id
 * @param {number} observerId
 */
function lom_unobserve(id, observerId) {
  _handle(id, function () {
    var obsId = parseInt(observerId);
    var st = observers[obsId];
    if (!st) return 'already-freed';
    if (st.timer_id) {
      try {
        st.timer_id.cancel();
      } catch (_) {}
    }
    /* istanbul ignore else -- defensive: lom_observe always populates api */
    if (st.api) {
      try {
        st.api.property = '';
      } catch (_) {}
      try {
        st.api = null;
      } catch (_) {}
    }
    delete observers[obsId];
    return 'done';
  });
}

// CJS export — only fires when this file is `require`d by a test runner.
// In Max [js] (the actual runtime) `module` is undefined and the assignment
// is skipped, leaving the top-level `function` declarations as the only
// exposure (which is what Max needs anyway). The `else` branch is
// unreachable from Jest, so we tell Istanbul to ignore it.
/* istanbul ignore else */
if (typeof module !== 'undefined') {
  module.exports = {
    _scheduleObserverFlush,
    _serializeForOutlet,
    lom_observe,
    lom_unobserve,
  };
}
