// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Track input / output routing (type + channel).

/**
 * Set a Track's routing dict prop (input_routing_type / output_routing_type
 * / input_routing_channel / output_routing_channel). The set call expects a
 * Dict whose identifier matches one in the corresponding available_<prop>s
 * list — we validate first to fail loudly on bad identifiers AND to preserve
 * the native identifier type (Live 12 uses ints for some channels, symbols
 * for others; the Dict round-trip must keep the original type).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {string} propName - One of the four routing prop names above.
 * @param {string} identifier
 */
function lom_set_track_routing(id, trackIndex, propName, identifier) {
  _handle(id, function () {
    var track = new LiveAPI(null, _trackPath(trackIndex));

    var prop = String(propName);
    var availName = 'available_' + prop + 's';
    var rawAvail = track.get(availName);
    var availStr = Array.isArray(rawAvail) && rawAvail.length === 1 ? rawAvail[0] : rawAvail;

    var avail = [];
    if (typeof availStr === 'string' && availStr.charAt(0) === '{') {
      try {
        var parsed = JSON.parse(availStr);
        avail = parsed[availName] || [];
      } catch (_) {}
    }

    var idStr = String(identifier);
    var match = null;
    for (var i = 0; i < avail.length; i++) {
      if (String(avail[i].identifier) === idStr) {
        match = avail[i];
        break;
      }
    }
    if (!match) {
      var have = [];
      for (var j = 0; j < avail.length; j++) {
        have.push(JSON.stringify(avail[j].identifier) + ' (' + avail[j].display_name + ')');
      }
      throw new Error(
        'No ' + prop + ' with identifier "' + idStr + '". Available: ' + have.join(', ')
      );
    }

    var d = new Dict();
    d.parse(JSON.stringify(match));
    track.set(prop, d);

    return JSON.stringify(match);
  });
}

/**
 * Read input_routing_{type,channel} or output_routing_{type,channel} on a
 * track plus their available_* lists. Outlet JSON
 *   { type: {current, available}, channel: {current, available} }.
 *
 * Live 12+ returns dict-typed properties as a JSON-string envelope ; older
 * versions returned alternating key/value lists (kept as fallback).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {string} side - 'input' or 'output'.
 */
function lom_get_track_routing(id, trackIndex, side) {
  _handle(id, function () {
    var track = new LiveAPI(null, _trackPath(trackIndex));
    var prefix = String(side);

    /**
     * @param {string} propName
     * @returns {unknown}
     */
    function readProp(propName) {
      var raw = track.get(propName);
      var val = Array.isArray(raw) && raw.length === 1 ? raw[0] : raw;
      if (typeof val === 'string' && val.charAt(0) === '{') {
        try {
          var parsed = JSON.parse(val);
          return parsed[propName] !== undefined ? parsed[propName] : parsed;
        } catch (_) {}
      }
      if (Array.isArray(val)) {
        var o = {};
        for (var i = 0; i < val.length; i += 2) o[val[i]] = val[i + 1];
        return o;
      }
      return val;
    }

    return JSON.stringify({
      type: {
        current: readProp(prefix + '_routing_type'),
        available: readProp('available_' + prefix + '_routing_types'),
      },
      channel: {
        current: readProp(prefix + '_routing_channel'),
        available: readProp('available_' + prefix + '_routing_channels'),
      },
    });
  });
}

// CJS export — only fires when this file is `require`d by a test runner.
// In Max [js] (the actual runtime) `module` is undefined and the assignment
// is skipped, leaving the top-level `function` declarations as the only
// exposure (which is what Max needs anyway). The `else` branch is
// unreachable from Jest, so we tell Istanbul to ignore it.
/* istanbul ignore else */
if (typeof module !== 'undefined') {
  module.exports = {
    lom_set_track_routing,
    lom_get_track_routing,
  };
}
