// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Session-level reads & selection: cue points, scenes, grooves,
// take lanes, group info, scale, control surfaces, current selection.

/**
 * Set the name of a cue point (resolved by index in Song.cue_points).
 *
 * @param {number} id
 * @param {number} cueIndex
 * @param {string} name
 */
function lom_set_cue_point_name(id, cueIndex, name) {
  _handle(id, function () {
    var cp = _byId(_resolveCueId(cueIndex));
    if (!cp) throw new Error('No cue point at index ' + cueIndex);
    cp.set('name', String(name));
    return 'done';
  });
}

/**
 * Set the time (beat position) of a cue point.
 *
 * @param {number} id
 * @param {number} cueIndex
 * @param {number} time
 */
function lom_set_cue_point_time(id, cueIndex, time) {
  _handle(id, function () {
    var cp = _byId(_resolveCueId(cueIndex));
    if (!cp) throw new Error('No cue point at index ' + cueIndex);
    cp.set('time', parseFloat(time));
    return 'done';
  });
}

/**
 * Jump the playhead to a cue point.
 *
 * @param {number} id
 * @param {number} cueIndex
 */
function lom_jump_to_cue(id, cueIndex) {
  _handle(id, function () {
    var cp = _byId(_resolveCueId(cueIndex));
    if (!cp) throw new Error('No cue point at index ' + cueIndex);
    cp.call('jump');
    return 'done';
  });
}

/**
 * Iterate Song.cue_points and outlet JSON `[{name, time}, ...]`.
 *
 * @param {number} id
 */
function lom_get_cue_points(id) {
  _handle(id, function () {
    var song = new LiveAPI(null, 'live_set');
    var out = [];
    _foreachChild(song, 'cue_points', function (cp) {
      out.push({
        name: String(_unwrap(cp.get('name'))),
        time: parseFloat(_unwrap(cp.get('time'))),
      });
    });
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON of all grooves in the groove pool. base is an int enum:
 * 0=1/4, 1=1/8, 2=1/8T, 3=1/16, 4=1/16T, 5=1/32.
 *
 * @param {number} id
 */
function lom_get_grooves(id) {
  _handle(id, function () {
    var pool = new LiveAPI(null, 'live_set groove_pool');
    var count = parseInt(pool.getcount('grooves'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var g = new LiveAPI(null, 'live_set groove_pool grooves ' + i);
      out.push({
        index: i,
        name: String(_unwrap(g.get('name')) || ''),
        base: parseInt(_unwrap(g.get('base'))),
        quantization_amount: parseFloat(_unwrap(g.get('quantization_amount'))),
        random_amount: parseFloat(_unwrap(g.get('random_amount'))),
        timing_amount: parseFloat(_unwrap(g.get('timing_amount'))),
        velocity_amount: parseFloat(_unwrap(g.get('velocity_amount'))),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON `[{index, name}, ...]` for take lanes of a track. TakeLane has
 * only a 'name' property and arrangement_clips child — name is the most
 * useful per-lane identifier.
 *
 * @param {number} id
 * @param {number} trackIndex
 */
function lom_get_take_lanes(id, trackIndex) {
  _handle(id, function () {
    var trackPath = _trackPath(trackIndex);
    var t = new LiveAPI(null, trackPath);
    var count = parseInt(t.getcount('take_lanes'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var lane = new LiveAPI(null, trackPath + ' take_lanes ' + i);
      out.push({
        index: i,
        name: String(_unwrap(lane.get('name')) || ''),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON of the current Song.View selection state:
 *   { selected_track_index, selected_scene_index, highlighted_clip_slot,
 *     detail_clip_path, selected_device_path, selected_chain_path }.
 * `_path` fields are LOM canonical paths or null.
 *
 * @param {number} id
 */
function lom_get_selection(id) {
  _handle(id, function () {
    var view = new LiveAPI(null, 'live_set view');
    /**
     * @param {Array} childRef
     * @returns {string|null}
     */
    function pathOf(childRef) {
      if (Array.isArray(childRef) && childRef.length >= 2 && childRef[0] === 'id') {
        var api = _byId(childRef[1]);
        if (!api) return null;
        return String(api.path || '').replace(/^"|"$/g, '') || null;
      }
      return null;
    }
    /**
     * @param {string|null} path
     * @param {string} kind
     * @returns {number}
     */
    function indexFromPath(path, kind) {
      if (!path) return -1;
      var re = new RegExp('live_set ' + kind + ' (\\d+)');
      var m = path.match(re);
      return m ? parseInt(m[1]) : -1;
    }
    var hcsPath = pathOf(view.get('highlighted_clip_slot'));
    var hcs = null;
    if (hcsPath) {
      var hm = hcsPath.match(/live_set tracks (\d+) clip_slots (\d+)/);
      if (hm) hcs = { track: parseInt(hm[1]), slot: parseInt(hm[2]) };
    }
    return JSON.stringify({
      selected_track_index: indexFromPath(pathOf(view.get('selected_track')), 'tracks'),
      selected_scene_index: indexFromPath(pathOf(view.get('selected_scene')), 'scenes'),
      highlighted_clip_slot: hcs,
      detail_clip_path: pathOf(view.get('detail_clip')),
      selected_device_path: pathOf(view.get('selected_parameter')),
      selected_chain_path: pathOf(view.get('selected_chain')),
    });
  });
}

/**
 * Select a track in Live's UI (Song.View.selected_track). Setting a
 * child-ref prop in jsliveapi takes the form view.set(prop, 'id', N).
 *
 * @param {number} id
 * @param {number} trackIndex
 */
function lom_select_track(id, trackIndex) {
  _handle(id, function () {
    var t = new LiveAPI(null, _trackPath(trackIndex));
    var tid = t.id;
    if (!tid || tid === 0 || tid === '0') throw new Error('No track at index ' + trackIndex);
    var view = new LiveAPI(null, 'live_set view');
    view.set('selected_track', 'id', tid);
    return 'done';
  });
}

/**
 * Select a scene in Live's UI.
 *
 * @param {number} id
 * @param {number} sceneIndex
 */
function lom_select_scene(id, sceneIndex) {
  _handle(id, function () {
    var s = new LiveAPI(null, 'live_set scenes ' + parseInt(sceneIndex));
    var sid = s.id;
    if (!sid || sid === 0 || sid === '0') throw new Error('No scene at index ' + sceneIndex);
    var view = new LiveAPI(null, 'live_set view');
    view.set('selected_scene', 'id', sid);
    return 'done';
  });
}

/**
 * Track group info bundle: {is_foldable, is_grouped, fold_state,
 * group_track_index} in one round-trip. group_track_index is -1 for
 * top-level tracks; otherwise we follow Track.group_track and parse its
 * canonical path to extract the parent's index.
 *
 * @param {number} id
 * @param {number} trackIndex
 */
function lom_get_track_group_info(id, trackIndex) {
  _handle(id, function () {
    var t = new LiveAPI(null, _trackPath(trackIndex));
    var info = {
      is_foldable: Boolean(parseInt(_unwrap(t.get('is_foldable')))),
      is_grouped: Boolean(parseInt(_unwrap(t.get('is_grouped')))),
      fold_state: parseInt(_unwrap(t.get('fold_state'))),
      group_track_index: -1,
    };
    if (info.is_grouped) {
      var gt = t.get('group_track');
      var gtId = Array.isArray(gt) && gt.length >= 2 && gt[0] === 'id' ? gt[1] : 0;
      var gtApi = _byId(gtId);
      if (gtApi) {
        var gtPath = String(gtApi.path || '').replace(/^"|"$/g, '');
        var matched = gtPath.match(/live_set tracks (\d+)/);
        if (matched) info.group_track_index = parseInt(matched[1]);
      }
    }
    return JSON.stringify(info);
  });
}

/**
 * Read all scale-related props in one round-trip (Live 12+). scale_intervals
 * may come back as a JSON-string envelope or a flat array depending on Live
 * version.
 *
 * @param {number} id
 */
function lom_get_scale(id) {
  _handle(id, function () {
    var s = new LiveAPI(null, 'live_set');
    var rawIntervals = s.get('scale_intervals');
    var intervals;
    var ival =
      Array.isArray(rawIntervals) && rawIntervals.length === 1 ? rawIntervals[0] : rawIntervals;
    if (typeof ival === 'string' && ival.charAt(0) === '{') {
      try {
        var parsed = JSON.parse(ival);
        intervals = parsed.scale_intervals !== undefined ? parsed.scale_intervals : parsed;
      } catch (_) {
        intervals = [];
      }
    } else if (Array.isArray(rawIntervals)) {
      intervals = rawIntervals.slice();
    } else {
      intervals = [];
    }
    return JSON.stringify({
      scale_name: String(_unwrap(s.get('scale_name')) || ''),
      root_note: parseInt(_unwrap(s.get('root_note'))),
      scale_mode: Boolean(parseInt(_unwrap(s.get('scale_mode')))),
      scale_intervals: intervals,
    });
  });
}

/**
 * Outlet JSON `[{index, type_name, is_connected}, ...]` for the active
 * control surfaces (hardware controllers mapped in Link/MIDI Preferences).
 * Empty slots have type_name = 'None' or empty.
 *
 * @param {number} id
 */
function lom_get_control_surfaces(id) {
  _handle(id, function () {
    var app = new LiveAPI();
    app.path = 'live_app';
    var count = parseInt(app.getcount('control_surfaces'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var cs = new LiveAPI(null, 'control_surfaces ' + i);
      var typeName = String(_unwrap(cs.get('type_name')) || '');
      out.push({
        index: i,
        type_name: typeName || 'None',
        is_connected: typeName !== '' && typeName !== 'None' && typeName !== '0',
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON list of control names (buttons/knobs/pads) exposed by a given
 * control surface.
 *
 * @param {number} id
 * @param {number} surfaceIndex
 */
function lom_get_control_surface_controls(id, surfaceIndex) {
  _handle(id, function () {
    var cs = new LiveAPI(null, 'control_surfaces ' + parseInt(surfaceIndex));
    var raw = cs.get('control_names');
    var names = Array.isArray(raw) ? raw : raw ? [raw] : [];
    return JSON.stringify(
      names.map(function (n) {
        return String(n);
      }),
    );
  });
}

// CJS export — only fires when this file is `require`d by a test runner.
// In Max [js] (the actual runtime) `module` is undefined and the assignment
// is skipped, leaving the top-level `function` declarations as the only
// exposure (which is what Max needs anyway). The `else` branch is
// unreachable from Jest, so we tell Istanbul to ignore it.
/* istanbul ignore else */
if (typeof module !== 'undefined') {
  module.exports = {
    lom_set_cue_point_name,
    lom_set_cue_point_time,
    lom_jump_to_cue,
    lom_get_cue_points,
    lom_get_grooves,
    lom_get_take_lanes,
    lom_get_selection,
    lom_select_track,
    lom_select_scene,
    lom_get_track_group_info,
    lom_get_scale,
    lom_get_control_surfaces,
    lom_get_control_surface_controls,
  };
}
