// AUTO-GENERATED — do not edit this file directly.
// Source files live in app/lom_router/ and are concatenated by
// tools/build/concat-lom.js. Edit there ; this file is regenerated
// by `npm run build` and on every save under app/lom_router/ when
// the dev server is running.

// Runs in Max [js] engine — NOT Node.js
// LiveAPI is globally available here

inlets = 1;
outlets = 1;


// ━━━ from 00_helpers.js ━━━

// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Helpers shared across domains: id resolution, child iteration, path
// construction, return-value normalization. All `_xxx` private helpers.

/**
 * Run `fn()` and outlet its return value as `lom_response id ok value`.
 * Any thrown Error becomes `lom_response id error message`. Absorbs the
 * try/catch boilerplate that every handler used to repeat, and lets
 * handlers signal user-facing errors with `throw new Error(msg)` instead
 * of an inline `outlet(0, 'lom_response', id, 'error', msg); return`.
 *
 * @param {number} id - Request id for the response envelope.
 * @param {() => unknown} fn - Body of the handler. Whatever it returns is
 *   the success payload (use 'done' for void operations).
 */
function _handle(id, fn) {
  try {
    outlet(0, 'lom_response', id, 'ok', fn());
  } catch (e) {
    outlet(0, 'lom_response', id, 'error', e.message);
  }
}

/**
 * Build a clip path from track+slot indices.
 *
 * @param {number} t
 * @param {number} s
 * @returns {string}
 */
function _clipPath(t, s) {
  return 'live_set tracks ' + parseInt(t) + ' clip_slots ' + parseInt(s) + ' clip';
}

/**
 * Build a clip-slot path from track+slot indices.
 *
 * @param {number} t
 * @param {number} s
 * @returns {string}
 */
function _slotPath(t, s) {
  return 'live_set tracks ' + parseInt(t) + ' clip_slots ' + parseInt(s);
}

/**
 * Build a track path from a track index.
 *
 * @param {number} t
 * @returns {string}
 */
function _trackPath(t) {
  return 'live_set tracks ' + parseInt(t);
}

/**
 * Build a device path from track + device index.
 *
 * @param {number} t
 * @param {number} d
 * @returns {string}
 */
function _devicePath(t, d) {
  return 'live_set tracks ' + parseInt(t) + ' devices ' + parseInt(d);
}

/**
 * Normalize a Live notes-API return value to a JSON string. Live 12+ returns
 * JSON directly; older versions returned a Dict name we have to fetch.
 *
 * @param {string|Array} raw - Either a JSON string starting with '{' or a Dict name (or array thereof).
 * @returns {string}
 */
function _dictReturnToJson(raw) {
  if (typeof raw === 'string' && raw.charAt(0) === '{') {
    return raw;
  }
  var dictName = Array.isArray(raw) ? raw[raw.length - 1] : raw;
  return new Dict(dictName).stringify();
}

/**
 * Map an io_type token to its corresponding child-list property name on a
 * Device. Returns null for unknown tokens.
 *
 * @param {string} ioType - 'audio_in' | 'audio_out' | 'midi_in' | 'midi_out'.
 * @returns {string|null}
 */
function _ioListProp(ioType) {
  return (
    {
      audio_in: 'audio_inputs',
      audio_out: 'audio_outputs',
      midi_in: 'midi_inputs',
      midi_out: 'midi_outputs',
    }[String(ioType)] || null
  );
}

/**
 * Build a LiveAPI from a numeric id. Returns null if the id is missing or
 * zero (LOM convention for "not present").
 *
 * @param {number|string} idValue
 * @returns {object|null}
 */
function _byId(idValue) {
  if (!idValue || idValue === 0 || idValue === '0') return null;
  return new LiveAPI(null, 'id', idValue);
}

/**
 * Resolve a single child's LiveAPI id by its index in the parent's child
 * list. Returns 0 if out of range — matches LOM's "not present" sentinel.
 *
 * @param {object} parent
 * @param {string} childKey
 * @param {number} index
 * @returns {number}
 */
function _resolveChildId(parent, childKey, index) {
  var ids = parent.get(childKey) || [];
  var pos = parseInt(index) * 2;
  if (pos + 1 >= ids.length || ids[pos] !== 'id') return 0;
  return ids[pos + 1];
}

/**
 * Iterate a parent's child list and call `fn(api, index)` for each child.
 * Returning false from fn breaks early. Children whose id is 0 are skipped.
 *
 * @param {object} parent
 * @param {string} childKey
 * @param {(api: object, index: number) => unknown} fn
 */
function _foreachChild(parent, childKey, fn) {
  var ids = parent.get(childKey) || [];
  for (var i = 0; i < ids.length; i += 2) {
    var api = _byId(ids[i + 1]);
    if (!api) continue;
    if (fn(api, i / 2) === false) break;
  }
}

/**
 * Specialized for CuePoint resolution. Kept as a thin wrapper because every
 * cue_point setter/method calls it.
 *
 * @param {number} cueIndex
 * @returns {number}
 */
function _resolveCueId(cueIndex) {
  var song = new LiveAPI(null, 'live_set');
  return _resolveChildId(song, 'cue_points', cueIndex);
}

/**
 * If `v` is an array, return its last element ; otherwise return it as-is.
 * Many LiveAPI getters return a single-element array — this normalizes them.
 *
 * @param {unknown} v
 * @returns {unknown}
 */
function _unwrap(v) {
  return Array.isArray(v) ? v[v.length - 1] : v;
}

/**
 * Path of a rack-class device on a track.
 *
 * @param {number} track
 * @param {number} devIdx
 * @returns {string}
 */
function _rackPath(track, devIdx) {
  return 'live_set tracks ' + parseInt(track) + ' devices ' + parseInt(devIdx);
}

/**
 * Path of a Chain inside a regular Rack.
 *
 * @param {number} track
 * @param {number} devIdx
 * @param {number} chainIdx
 * @returns {string}
 */
function _chainPath(track, devIdx, chainIdx) {
  return _rackPath(track, devIdx) + ' chains ' + parseInt(chainIdx);
}

/**
 * Path of a DrumPad inside a Drum Rack. padIdx is the canonical drum_pads
 * index (= MIDI note 0..127).
 *
 * @param {number} track
 * @param {number} devIdx
 * @param {number} padIdx
 * @returns {string}
 */
function _drumPadPath(track, devIdx, padIdx) {
  return _rackPath(track, devIdx) + ' drum_pads ' + parseInt(padIdx);
}

// ━━━ from 10_dispatch.js ━━━

// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Dispatcher entry points: generic lom_request (get/set/call any LOM path),
// peer scan, full session state snapshot.

/**
 * Generic LOM dispatcher: get / set / call against any LOM path. Args layout
 * is (id, op, nParts, ...pathParts, prop, ...extras). Outlets `lom_response
 * id ok value` or `lom_response id error message`.
 */
function lom_request() {
  var args = Array.prototype.slice.call(arguments);
  var id = args[0];
  var op = args[1];
  var nParts = parseInt(args[2]);
  var pathParts = args.slice(3, 3 + nParts);
  var lomPath = pathParts.join(' ');
  var prop = args[3 + nParts];
  // 'get' has no extras; 'set' has 1 (the value); 'call' has 0..N (method args)
  var extras = args.slice(3 + nParts + 1);

  _handle(id, function () {
    var api = new LiveAPI(null, lomPath);
    if (op === 'get') return _unwrap(api.get(prop));
    if (op === 'set') {
      api.set(prop, extras[0]);
      return 'done';
    }
    if (op === 'call') {
      var result = extras.length > 0 ? api.call.apply(api, [prop].concat(extras)) : api.call(prop);
      return result !== undefined ? result : 'done';
    }
    throw new Error('unsupported op: ' + op);
  });
}

/**
 * Scan LiveSet (tracks + return_tracks + master) for agent4live peer devices.
 * Marker = a `live.numbox` named `__agent4live_marker__` that every device
 * carries. Outlets JSON `{selfId, peers: [{deviceId, trackName, position, isSelf}, ...]}`.
 *
 * @param {number} id
 */
function lom_scan_peers(id) {
  _handle(id, function () {
    var selfApi = new LiveAPI(null, 'this_device');
    var selfId = selfApi.id;

    var MARKER_NAME = '__agent4live_marker__';
    var peers = [];

    /**
     * @param {object} track
     * @param {string} trackName
     */
    function scanDevicesOnTrack(track, trackName) {
      var pos = 0;
      _foreachChild(track, 'devices', function (device) {
        var devId = device.id;
        _foreachChild(device, 'parameters', function (param) {
          if (String(param.get('name')) === MARKER_NAME) {
            peers.push({
              deviceId: devId,
              trackName: trackName,
              position: pos,
              isSelf: devId == selfId,
            });
            return false; // stop param scan, marker found
          }
        });
        pos++;
      });
    }

    var liveSet = new LiveAPI(null, 'live_set');
    _foreachChild(liveSet, 'tracks', function (trackApi) {
      scanDevicesOnTrack(trackApi, String(trackApi.get('name')));
    });
    _foreachChild(liveSet, 'return_tracks', function (returnApi) {
      scanDevicesOnTrack(returnApi, String(returnApi.get('name')));
    });

    var masterApi = new LiveAPI(null, 'live_set master_track');
    scanDevicesOnTrack(masterApi, String(masterApi.get('name')));

    return JSON.stringify({ selfId: selfId, peers: peers });
  });
}

/**
 * Full session snapshot: tempo, is_playing, list of tracks (index, name,
 * is_midi_track, muted), list of scenes (index, name).
 *
 * @param {number} id
 */
function lom_session_state(id) {
  _handle(id, function () {
    var song = new LiveAPI(null, 'live_set');

    var tracks = [];
    _foreachChild(song, 'tracks', function (track, index) {
      tracks.push({
        index: index,
        name: String(track.get('name')),
        is_midi_track: Boolean(parseInt(_unwrap(track.get('is_midi_track')))),
        muted: Boolean(parseInt(_unwrap(track.get('mute')))),
      });
    });

    var scenes = [];
    _foreachChild(song, 'scenes', function (scene, index) {
      scenes.push({
        index: index,
        name: String(scene.get('name')),
      });
    });

    return JSON.stringify({
      tempo: _unwrap(song.get('tempo')),
      is_playing: Boolean(_unwrap(song.get('is_playing'))),
      track_count: tracks.length,
      scene_count: scenes.length,
      tracks: tracks,
      scenes: scenes,
    });
  });
}

// ━━━ from 20_clips.js ━━━

// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Clip operations: notes (read/add/replace/modify/remove/duplicate),
// warp markers, audio info, envelope clearing, arrangement-clip lifecycle,
// session-clip duplication, groove assignment.

/**
 * Read notes inside a region of a clip (Live 11+ get_notes_extended).
 * Outlets the result Dict serialized as JSON.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} fromPitch
 * @param {number} pitchSpan
 * @param {number} fromTime
 * @param {number} timeSpan
 */
function lom_get_clip_notes(id, trackIndex, slotIndex, fromPitch, pitchSpan, fromTime, timeSpan) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var raw = clip.call(
      'get_notes_extended',
      parseInt(fromPitch),
      parseInt(pitchSpan),
      parseFloat(fromTime),
      parseFloat(timeSpan)
    );
    return _dictReturnToJson(raw);
  });
}

/**
 * Wipe every note in the clip and lay down a new set (atomic). notesJson
 * shape matches lom_add_clip's notes param.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} notesJson - JSON array of {pitch,time,duration,velocity?,mute?}.
 */
function lom_replace_clip_notes(id, trackIndex, slotIndex, notesJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var clipLength = parseFloat(clip.get('length'));

    // Wipe everything in the clip's full pitch and time range.
    clip.call('remove_notes_extended', 0, 128, 0, clipLength);

    var notes = JSON.parse(String(notesJson));
    if (notes.length > 0) {
      var spec = { notes: [] };
      for (var i = 0; i < notes.length; i++) {
        var n = notes[i];
        spec.notes.push({
          pitch: parseInt(n.pitch),
          start_time: parseFloat(n.time),
          duration: parseFloat(n.duration),
          velocity: parseInt(n.velocity || 100),
          mute: parseInt(n.mute || 0),
        });
      }
      var d = new Dict();
      d.parse(JSON.stringify(spec));
      clip.call('add_new_notes', d);
    }

    return 'done';
  });
}

/**
 * Modify existing notes by note_id (Live 11+). Only listed properties change;
 * notes not in clip are silently ignored.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} notesJson - { notes: [{ note_id, ...changes }, ...] } as JSON.
 */
function lom_apply_note_modifications(id, trackIndex, slotIndex, notesJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var d = new Dict();
    d.parse(String(notesJson));
    clip.call('apply_note_modifications', d);
    return 'done';
  });
}

/**
 * Outlet JSON of all notes in a clip (Live 11+ get_all_notes_extended).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 */
function lom_get_all_notes(id, trackIndex, slotIndex) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    return _dictReturnToJson(clip.call('get_all_notes_extended'));
  });
}

/**
 * Outlet JSON of the currently selected notes in a clip
 * (Live 11+ get_selected_notes_extended).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 */
function lom_get_selected_notes(id, trackIndex, slotIndex) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    return _dictReturnToJson(clip.call('get_selected_notes_extended'));
  });
}

/**
 * Outlet JSON of specific notes by note_id. Live's get_notes_by_id accepts
 * a varargs list of atom note IDs, which we splat from the JSON array.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} idsJson - JSON array of note_id integers.
 */
function lom_get_notes_by_id(id, trackIndex, slotIndex, idsJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var ids = JSON.parse(String(idsJson));
    return _dictReturnToJson(clip.call.apply(clip, ['get_notes_by_id'].concat(ids)));
  });
}

/**
 * Add a warp marker on an audio clip. At least one of beat_time / sample_time
 * must be provided; the other is sent as NaN to mean "omit".
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} beatTime - NaN means "omit".
 * @param {number} sampleTime - NaN means "omit".
 */
function lom_add_warp_marker(id, trackIndex, slotIndex, beatTime, sampleTime) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var spec = {};
    var bt = parseFloat(beatTime);
    var st = parseFloat(sampleTime);
    if (!isNaN(bt)) spec.beat_time = bt;
    if (!isNaN(st)) spec.sample_time = st;
    if (Object.keys(spec).length === 0) {
      throw new Error('add_warp_marker: at least one of beat_time / sample_time required');
    }
    var d = new Dict();
    d.parse(JSON.stringify(spec));
    clip.call('add_warp_marker', d);
    return 'done';
  });
}

/**
 * Create a new MIDI clip in a session slot and optionally seed it with notes.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} clipLength - In beats.
 * @param {string} notesJson - JSON array of {pitch,time,duration,velocity?,mute?} (may be []).
 */
function lom_add_clip(id, trackIndex, slotIndex, clipLength, notesJson) {
  _handle(id, function () {
    var notes = JSON.parse(String(notesJson));
    var slotPath = _slotPath(trackIndex, slotIndex);
    var slot = new LiveAPI(null, slotPath);
    slot.call('create_clip', parseFloat(clipLength));

    if (notes.length > 0) {
      var clip = new LiveAPI(null, slotPath + ' clip');
      var spec = { notes: [] };
      for (var i = 0; i < notes.length; i++) {
        var n = notes[i];
        spec.notes.push({
          pitch: parseInt(n.pitch),
          start_time: parseFloat(n.time),
          duration: parseFloat(n.duration),
          velocity: parseInt(n.velocity || 100),
          mute: parseInt(n.mute || 0),
        });
      }
      var d = new Dict();
      d.parse(JSON.stringify(spec));
      clip.call('add_new_notes', d);
    }

    return 'done';
  });
}

/**
 * Clear automation envelope for ONE specific DeviceParameter on a clip.
 * Resolves the param via path (track / device / parameter index), then
 * passes its id to clip.clear_envelope.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} deviceIndex
 * @param {number} paramIndex
 */
function lom_clear_clip_envelope(id, trackIndex, slotIndex, deviceIndex, paramIndex) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var paramPath = _devicePath(trackIndex, deviceIndex) + ' parameters ' + parseInt(paramIndex);
    var p = new LiveAPI(null, paramPath);
    var pid = p.id;
    if (!pid || pid === 0 || pid === '0') throw new Error('No parameter at ' + paramPath);
    clip.call('clear_envelope', 'id', pid);
    return 'done';
  });
}

/**
 * Track.duplicate_clip_to_arrangement(clip, destination_time). The clip param
 * is a LiveAPI clip ID, so we resolve it from track+slot first.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} destTime
 */
function lom_duplicate_clip_to_arrangement(id, trackIndex, slotIndex, destTime) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var clipId = clip.id;
    if (!clipId || clipId === 0 || clipId === '0') {
      throw new Error('No clip at track ' + trackIndex + ', slot ' + slotIndex);
    }
    var track = new LiveAPI(null, _trackPath(trackIndex));
    track.call('duplicate_clip_to_arrangement', 'id', clipId, parseFloat(destTime));
    return 'done';
  });
}

/**
 * Track.delete_clip(clip) — for arrangement clips. Resolves clip id from
 * track.arrangement_clips[N], then calls Track.delete_clip with that id.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} arrClipIndex
 */
function lom_delete_arrangement_clip(id, trackIndex, arrClipIndex) {
  _handle(id, function () {
    var track = new LiveAPI(null, _trackPath(trackIndex));
    var clips = track.get('arrangement_clips') || [];
    // arrangement_clips comes back as alternating ['id', N] pairs.
    var idx = parseInt(arrClipIndex);
    var pos = idx * 2;
    if (pos + 1 >= clips.length || clips[pos] !== 'id') {
      throw new Error('Arrangement clip index ' + idx + ' out of range');
    }
    track.call('delete_clip', 'id', clips[pos + 1]);
    return 'done';
  });
}

/**
 * Remove notes by ID (Live 11+). Variadic atoms call.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} idsJson - JSON array of note_id integers.
 */
function lom_remove_notes_by_id(id, trackIndex, slotIndex, idsJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var ids = JSON.parse(String(idsJson));
    if (!Array.isArray(ids) || ids.length === 0) return 'no-op';
    clip.call.apply(clip, ['remove_notes_by_id'].concat(ids));
    return 'done';
  });
}

/**
 * Duplicate notes by ID (Live 11+). Uses the dict form for optional
 * destination_time + transposition_amount support.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} paramsJson - { note_ids, destination_time?, transposition_amount? }.
 */
function lom_duplicate_notes_by_id(id, trackIndex, slotIndex, paramsJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var p = JSON.parse(String(paramsJson));
    var spec = { note_ids: p.note_ids };
    if (p.destination_time !== undefined && p.destination_time !== null)
      spec.destination_time = p.destination_time;
    if (p.transposition_amount !== undefined && p.transposition_amount !== null)
      spec.transposition_amount = p.transposition_amount;
    var d = new Dict();
    d.parse(JSON.stringify(spec));
    clip.call('duplicate_notes_by_id', d);
    return 'done';
  });
}

/**
 * Add notes to an EXISTING clip (vs replace_clip_notes which wipes first).
 * Outlets list of note IDs of the added notes (Live 11+) as JSON.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {string} notesJson - JSON array (may be empty).
 */
function lom_add_notes_to_clip(id, trackIndex, slotIndex, notesJson) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var notes = JSON.parse(String(notesJson));
    if (!Array.isArray(notes) || notes.length === 0) return '[]';
    var spec = { notes: [] };
    for (var i = 0; i < notes.length; i++) {
      var n = notes[i];
      var entry = {
        pitch: parseInt(n.pitch),
        start_time: parseFloat(n.start_time !== undefined ? n.start_time : n.time),
        duration: parseFloat(n.duration),
        velocity: parseFloat(n.velocity !== undefined ? n.velocity : 100),
      };
      if (n.mute !== undefined) entry.mute = parseInt(n.mute);
      if (n.probability !== undefined) entry.probability = parseFloat(n.probability);
      if (n.velocity_deviation !== undefined)
        entry.velocity_deviation = parseFloat(n.velocity_deviation);
      if (n.release_velocity !== undefined) entry.release_velocity = parseFloat(n.release_velocity);
      spec.notes.push(entry);
    }
    var d = new Dict();
    d.parse(JSON.stringify(spec));
    var raw = clip.call('add_new_notes', d);
    // add_new_notes returns the list of note IDs of added notes.
    var ids = Array.isArray(raw) ? raw : raw ? [raw] : [];
    return JSON.stringify(ids);
  });
}

/**
 * Duplicate a session clip to another slot. Resolves target clip_slot ref
 * from track + slot indices, then ClipSlot.duplicate_clip_to(target_slot).
 *
 * @param {number} id
 * @param {number} srcTrack
 * @param {number} srcSlot
 * @param {number} dstTrack
 * @param {number} dstSlot
 */
function lom_duplicate_clip_to_slot(id, srcTrack, srcSlot, dstTrack, dstSlot) {
  _handle(id, function () {
    var src = new LiveAPI(null, _slotPath(srcTrack, srcSlot));
    var dstPath = _slotPath(dstTrack, dstSlot);
    var dst = new LiveAPI(null, dstPath);
    var dstId = dst.id;
    if (!dstId || dstId === 0 || dstId === '0') throw new Error('No clip slot at ' + dstPath);
    src.call('duplicate_clip_to', 'id', dstId);
    return 'done';
  });
}

/**
 * Assign a groove to a clip (or clear it if grooveIndex < 0). Clip.groove is
 * a child-ref prop set via clip.set('groove', 'id', N).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 * @param {number} grooveIndex - Negative means "clear".
 */
function lom_set_clip_groove(id, trackIndex, slotIndex, grooveIndex) {
  _handle(id, function () {
    var clip = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    if (parseInt(grooveIndex) < 0) {
      clip.set('groove', 'id', 0);
      return 'cleared';
    }
    var g = new LiveAPI(null, 'live_set groove_pool grooves ' + parseInt(grooveIndex));
    var gid = g.id;
    if (!gid || gid === 0 || gid === '0') throw new Error('No groove at index ' + grooveIndex);
    clip.set('groove', 'id', gid);
    return 'done';
  });
}

/**
 * Read all audio-clip-relevant props in one round-trip. Falls back gracefully
 * for MIDI clips where audio props don't exist (returns is_audio_clip=false).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 */
function lom_get_clip_audio_info(id, trackIndex, slotIndex) {
  _handle(id, function () {
    var c = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var isAudio = Boolean(parseInt(_unwrap(c.get('is_audio_clip'))));
    var info = { is_audio_clip: isAudio };
    if (isAudio) {
      info.file_path = String(_unwrap(c.get('file_path')) || '');
      info.sample_length = parseInt(_unwrap(c.get('sample_length')));
      info.sample_rate = parseFloat(_unwrap(c.get('sample_rate')));
      info.warping = Boolean(parseInt(_unwrap(c.get('warping'))));
      info.warp_mode = parseInt(_unwrap(c.get('warp_mode')));
      info.gain = parseFloat(_unwrap(c.get('gain')));
      info.pitch_coarse = parseInt(_unwrap(c.get('pitch_coarse')));
      info.pitch_fine = parseFloat(_unwrap(c.get('pitch_fine')));
      info.start_marker = parseFloat(_unwrap(c.get('start_marker')));
      info.end_marker = parseFloat(_unwrap(c.get('end_marker')));
      info.ram_mode = Boolean(parseInt(_unwrap(c.get('ram_mode'))));
    }
    return JSON.stringify(info);
  });
}

/**
 * Read warp markers of an audio clip. Clip.warp_markers returns a Dict with
 * pairs of sample_time / beat_time. Same Live 12 vs 11 envelope situation
 * as the note Dict ops — use _dictReturnToJson.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} slotIndex
 */
function lom_get_warp_markers(id, trackIndex, slotIndex) {
  _handle(id, function () {
    var c = new LiveAPI(null, _clipPath(trackIndex, slotIndex));
    var raw = c.get('warp_markers');
    var val = Array.isArray(raw) && raw.length === 1 ? raw[0] : raw;
    if (typeof val === 'string' && val.charAt(0) === '{') {
      // Live 12+: JSON string envelope. Unwrap the {warp_markers: ...} key.
      try {
        var parsed = JSON.parse(val);
        return JSON.stringify(parsed.warp_markers !== undefined ? parsed.warp_markers : parsed);
      } catch (_) {}
    }
    // Fallback: try the Dict-name pattern (older Live).
    return _dictReturnToJson(raw);
  });
}

// ━━━ from 30_devices.js ━━━

// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Device operations: device list, parameter list, move device, IO routings
// for Max-for-Live and plugin devices.

/**
 * Unwrap a LiveAPI dict-typed property: Live 12+ returns a JSON-string
 * envelope `{"<prop>": value}` ; older Live returns alternating key/value
 * lists or single-element arrays. Returns the inner value.
 *
 * @param {object} api
 * @param {string} propName
 * @returns {unknown}
 */
function _unwrapDictProp(api, propName) {
  var raw = api.get(propName);
  var val = Array.isArray(raw) && raw.length === 1 ? raw[0] : raw;
  if (typeof val === 'string' && val.charAt(0) === '{') {
    try {
      var parsed = JSON.parse(val);
      return parsed[propName] !== undefined ? parsed[propName] : parsed;
    } catch (_) {}
  }
  if (Array.isArray(val)) {
    var o = {};
    for (var i = 0; i < val.length; i += 2) o[val[i]] = val[i + 1];
    return o;
  }
  return val;
}

/**
 * Outlet JSON of a device's IO routings (audio / midi, in / out). Each
 * DeviceIO entry has its current routing_type, routing_channel, plus the
 * available_* lists for those props.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} deviceIndex
 */
function lom_get_device_io_routings(id, trackIndex, deviceIndex) {
  _handle(id, function () {
    var devPath = _devicePath(trackIndex, deviceIndex);
    var dev = new LiveAPI(null, devPath);
    /**
     * @param {string} listProp
     * @returns {Array|null}
     */
    function readIoList(listProp) {
      var count = 0;
      try {
        count = parseInt(dev.getcount(listProp));
      } catch (_) {
        return null;
      }
      if (!count) return [];
      var out = [];
      for (var i = 0; i < count; i++) {
        var io = new LiveAPI(null, devPath + ' ' + listProp + ' ' + i);
        out.push({
          index: i,
          routing_type: _unwrapDictProp(io, 'routing_type'),
          routing_channel: _unwrapDictProp(io, 'routing_channel'),
          available_types: _unwrapDictProp(io, 'available_routing_types'),
          available_channels: _unwrapDictProp(io, 'available_routing_channels'),
        });
      }
      return out;
    }
    return JSON.stringify({
      audio_inputs: readIoList('audio_inputs'),
      audio_outputs: readIoList('audio_outputs'),
      midi_inputs: readIoList('midi_inputs'),
      midi_outputs: readIoList('midi_outputs'),
    });
  });
}

/**
 * Set a Dict-typed property (routing_type or routing_channel) on a DeviceIO.
 * Validates against the device's available_<prop>s list and preserves the
 * native identifier type (Live 12 returns ints for some channels, symbols
 * for others — Dict round-trip must keep that type).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} deviceIndex
 * @param {string} ioType - 'audio_in' | 'audio_out' | 'midi_in' | 'midi_out'.
 * @param {number} ioIndex
 * @param {string} propName - 'routing_type' or 'routing_channel'.
 * @param {string} identifier
 */
function _setDeviceIoDictProp(id, trackIndex, deviceIndex, ioType, ioIndex, propName, identifier) {
  _handle(id, function () {
    var listProp = _ioListProp(ioType);
    if (!listProp) throw new Error('invalid io_type: ' + ioType);
    var ioPath = _devicePath(trackIndex, deviceIndex) + ' ' + listProp + ' ' + parseInt(ioIndex);
    var io = new LiveAPI(null, ioPath);
    var availName = 'available_' + propName + 's';
    var rawAvail = io.get(availName);
    var availStr = Array.isArray(rawAvail) && rawAvail.length === 1 ? rawAvail[0] : rawAvail;
    var avail = [];
    if (typeof availStr === 'string' && availStr.charAt(0) === '{') {
      try {
        var parsed = JSON.parse(availStr);
        avail = parsed[availName] || [];
      } catch (_) {}
    }
    var idStr = String(identifier);
    var match = null;
    for (var i = 0; i < avail.length; i++) {
      if (String(avail[i].identifier) === idStr) {
        match = avail[i];
        break;
      }
    }
    if (!match) {
      var have = [];
      for (var j = 0; j < avail.length; j++) {
        have.push(JSON.stringify(avail[j].identifier) + ' (' + avail[j].display_name + ')');
      }
      throw new Error(
        'No ' + propName + ' with identifier "' + idStr + '". Available: ' + have.join(', ')
      );
    }
    var d = new Dict();
    d.parse(JSON.stringify(match));
    io.set(propName, d);
    return JSON.stringify(match);
  });
}

/**
 * @param {number} id
 * @param {number} t
 * @param {number} d
 * @param {string} ioType
 * @param {number} ioIdx
 * @param {string} identifier
 */
function lom_set_device_io_routing_type(id, t, d, ioType, ioIdx, identifier) {
  _setDeviceIoDictProp(id, t, d, ioType, ioIdx, 'routing_type', identifier);
}

/**
 * @param {number} id
 * @param {number} t
 * @param {number} d
 * @param {string} ioType
 * @param {number} ioIdx
 * @param {string} identifier
 */
function lom_set_device_io_routing_channel(id, t, d, ioType, ioIdx, identifier) {
  _setDeviceIoDictProp(id, t, d, ioType, ioIdx, 'routing_channel', identifier);
}

/**
 * Outlet JSON `[{index, name, class_name}, ...]` for every device on a track.
 * Uses getcount('devices') to dodge the "empty track returns ['id', 0]"
 * sentinel and addresses each device by canonical path (more robust to
 * dangling LiveAPI IDs).
 *
 * @param {number} id
 * @param {number} trackIndex
 */
function lom_get_track_devices(id, trackIndex) {
  _handle(id, function () {
    var trackPath = _trackPath(trackIndex);
    var track = new LiveAPI(null, trackPath);
    var count = parseInt(track.getcount('devices'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var dev = new LiveAPI(null, trackPath + ' devices ' + i);
      out.push({
        index: i,
        name: String(_unwrap(dev.get('name'))),
        class_name: String(_unwrap(dev.get('class_name'))),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON `[{index, name, value, min, max, is_quantized, is_enabled,
 * value_items?}, ...]` for every DeviceParameter on a device. value_items
 * (the discrete labels) is included only for quantized params.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} deviceIndex
 */
function lom_get_device_params(id, trackIndex, deviceIndex) {
  _handle(id, function () {
    var devPath = _devicePath(trackIndex, deviceIndex);
    var dev = new LiveAPI(null, devPath);
    var count = parseInt(dev.getcount('parameters'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var p = new LiveAPI(null, devPath + ' parameters ' + i);
      var entry = {
        index: i,
        name: String(_unwrap(p.get('name'))),
        value: parseFloat(_unwrap(p.get('value'))),
        min: parseFloat(_unwrap(p.get('min'))),
        max: parseFloat(_unwrap(p.get('max'))),
        is_quantized: Boolean(parseInt(_unwrap(p.get('is_quantized')))),
        is_enabled: Boolean(parseInt(_unwrap(p.get('is_enabled')))),
      };
      if (entry.is_quantized) {
        var items = p.get('value_items');
        if (Array.isArray(items)) {
          entry.value_items = items.map(function (x) {
            return String(x);
          });
        }
      }
      out.push(entry);
    }
    return JSON.stringify(out);
  });
}

/**
 * Move a device from a source track/index to a target track at a given
 * position. Song.move_device(device, target_track, target_position).
 *
 * @param {number} id
 * @param {number} fromTrack
 * @param {number} fromIdx
 * @param {number} toTrack
 * @param {number} toPosition
 */
function lom_move_device(id, fromTrack, fromIdx, toTrack, toPosition) {
  _handle(id, function () {
    var srcPath = _devicePath(fromTrack, fromIdx);
    var src = new LiveAPI(null, srcPath);
    var srcId = src.id;
    if (!srcId || srcId === 0 || srcId === '0') throw new Error('No device at ' + srcPath);
    var dstPath = _trackPath(toTrack);
    var dst = new LiveAPI(null, dstPath);
    var dstId = dst.id;
    if (!dstId || dstId === 0 || dstId === '0') throw new Error('No track at ' + dstPath);
    var song = new LiveAPI(null, 'live_set');
    song.call('move_device', 'id', srcId, 'id', dstId, parseInt(toPosition));
    return 'done';
  });
}

/**
 * Select a device in Live's UI by track + device index. Calls
 * Song.View.select_device(id) — the documented method takes a Device id, so
 * we resolve the LOM path to its id first, then dispatch.
 *
 * Use case: programmatic hot-swap workflow. Compose with toggle_browse() +
 * browser_load_item(path) to replace a device's preset without manual UI
 * focus. Sequence: select_device → toggle_browse → browser_load_item →
 * toggle_browse.
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {number} deviceIndex
 */
function lom_select_device(id, trackIndex, deviceIndex) {
  _handle(id, function () {
    var d = new LiveAPI(null, _trackPath(trackIndex) + ' devices ' + parseInt(deviceIndex));
    var did = d.id;
    if (!did || did === 0 || did === '0') {
      throw new Error('No device at track ' + trackIndex + ' index ' + deviceIndex);
    }
    var view = new LiveAPI(null, 'live_set view');
    view.call('select_device', did);
    return 'done';
  });
}

// ━━━ from 40_racks.js ━━━

// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Rack devices: chain listing, drum pad listing, chain/pad device drilldown,
// macros (read / add / remove / randomize), rack variations, drum-chain props.

/**
 * Read chain props (regular Rack chain or DrumPad chain — same Chain class).
 *
 * @param {string} chainPath
 * @param {number} chainIdx
 * @returns {object}
 */
function _readChain(chainPath, chainIdx) {
  var c = new LiveAPI(null, chainPath);
  return {
    chain_idx: chainIdx,
    name: String(_unwrap(c.get('name')) || ''),
    color: parseInt(_unwrap(c.get('color'))),
    mute: Boolean(parseInt(_unwrap(c.get('mute')))),
    solo: Boolean(parseInt(_unwrap(c.get('solo')))),
    muted_via_solo: Boolean(parseInt(_unwrap(c.get('muted_via_solo')))),
    has_audio_input: Boolean(parseInt(_unwrap(c.get('has_audio_input')))),
    has_audio_output: Boolean(parseInt(_unwrap(c.get('has_audio_output')))),
    has_midi_input: Boolean(parseInt(_unwrap(c.get('has_midi_input')))),
    has_midi_output: Boolean(parseInt(_unwrap(c.get('has_midi_output')))),
  };
}

/**
 * Outlet JSON list of chains in a regular Rack (Audio Effect Rack, Instrument
 * Rack). Returns [] for Drum Racks (use lom_get_drum_pads instead) or
 * non-rack devices.
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_get_rack_chains(id, track, devIdx) {
  _handle(id, function () {
    var rack = new LiveAPI(null, _rackPath(track, devIdx));
    var count = parseInt(rack.getcount('chains'));
    var out = [];
    for (var i = 0; i < count; i++) {
      out.push(_readChain(_chainPath(track, devIdx, i), i));
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON list of drum pads in a Drum Rack. With `onlyVisible=1`, returns
 * only the 16 pads visible in the matrix view ; otherwise the full 0..127 list.
 * Each entry: { pad_idx, name, note, mute, solo, chain_count } (pad_idx is
 * always the canonical drum_pads index = MIDI note, regardless of mode).
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} onlyVisible - 1 to filter to visible_drum_pads.
 */
function lom_get_drum_pads(id, track, devIdx, onlyVisible) {
  _handle(id, function () {
    var rackPath = _rackPath(track, devIdx);
    var rack = new LiveAPI(null, rackPath);
    var listProp = parseInt(onlyVisible) === 1 ? 'visible_drum_pads' : 'drum_pads';
    var count = parseInt(rack.getcount(listProp));
    var out = [];
    for (var i = 0; i < count; i++) {
      var padPath =
        parseInt(onlyVisible) === 1
          ? rackPath + ' visible_drum_pads ' + i
          : _drumPadPath(track, devIdx, i);
      var p = new LiveAPI(null, padPath);
      var note = parseInt(_unwrap(p.get('note')));
      if (isNaN(note) || note < 0) continue;
      out.push({
        pad_idx: note,
        name: String(_unwrap(p.get('name')) || ''),
        note: note,
        mute: Boolean(parseInt(_unwrap(p.get('mute')))),
        solo: Boolean(parseInt(_unwrap(p.get('solo')))),
        chain_count: parseInt(p.getcount('chains')),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON list of devices inside a regular Rack chain at depth 1.
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} chainIdx
 */
function lom_get_chain_devices(id, track, devIdx, chainIdx) {
  _handle(id, function () {
    var chainPath = _chainPath(track, devIdx, chainIdx);
    var chain = new LiveAPI(null, chainPath);
    var count = parseInt(chain.getcount('devices'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var d = new LiveAPI(null, chainPath + ' devices ' + i);
      out.push({
        index: i,
        name: String(_unwrap(d.get('name')) || ''),
        class_name: String(_unwrap(d.get('class_name')) || ''),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON list of chains nested inside a DrumPad. DrumPad chains are
 * DrumChain instances (Chain props + in_note / out_note / choke_group).
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} padIdx
 */
function lom_get_drum_pad_chains(id, track, devIdx, padIdx) {
  _handle(id, function () {
    var padPath = _drumPadPath(track, devIdx, padIdx);
    var pad = new LiveAPI(null, padPath);
    var count = parseInt(pad.getcount('chains'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var c = new LiveAPI(null, padPath + ' chains ' + i);
      out.push({
        chain_idx: i,
        name: String(_unwrap(c.get('name')) || ''),
        mute: Boolean(parseInt(_unwrap(c.get('mute')))),
        solo: Boolean(parseInt(_unwrap(c.get('solo')))),
        in_note: parseInt(_unwrap(c.get('in_note'))),
        out_note: parseInt(_unwrap(c.get('out_note'))),
        choke_group: parseInt(_unwrap(c.get('choke_group'))),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON list of devices inside a DrumPad's chain (1 level deeper than
 * lom_get_chain_devices).
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} padIdx
 * @param {number} chainIdx
 */
function lom_get_drum_pad_chain_devices(id, track, devIdx, padIdx, chainIdx) {
  _handle(id, function () {
    var chainPath = _drumPadPath(track, devIdx, padIdx) + ' chains ' + parseInt(chainIdx);
    var chain = new LiveAPI(null, chainPath);
    var count = parseInt(chain.getcount('devices'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var d = new LiveAPI(null, chainPath + ' devices ' + i);
      out.push({
        index: i,
        name: String(_unwrap(d.get('name')) || ''),
        class_name: String(_unwrap(d.get('class_name')) || ''),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Generic device-params reader at any path — shared by chain & drum-pad-chain
 * param tools (logic mirrors lom_get_device_params).
 *
 * @param {string} devPath
 * @returns {Array}
 */
function _readDeviceParams(devPath) {
  var dev = new LiveAPI(null, devPath);
  var count = parseInt(dev.getcount('parameters'));
  var out = [];
  for (var i = 0; i < count; i++) {
    var p = new LiveAPI(null, devPath + ' parameters ' + i);
    var entry = {
      index: i,
      name: String(_unwrap(p.get('name'))),
      value: parseFloat(_unwrap(p.get('value'))),
      min: parseFloat(_unwrap(p.get('min'))),
      max: parseFloat(_unwrap(p.get('max'))),
      is_quantized: Boolean(parseInt(_unwrap(p.get('is_quantized')))),
      is_enabled: Boolean(parseInt(_unwrap(p.get('is_enabled')))),
    };
    if (entry.is_quantized) {
      var items = p.get('value_items');
      if (Array.isArray(items))
        entry.value_items = items.map(function (x) {
          return String(x);
        });
    }
    out.push(entry);
  }
  return out;
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} chainIdx
 * @param {number} subDevIdx
 */
function lom_get_chain_device_params(id, track, devIdx, chainIdx, subDevIdx) {
  _handle(id, function () {
    var devPath = _chainPath(track, devIdx, chainIdx) + ' devices ' + parseInt(subDevIdx);
    return JSON.stringify(_readDeviceParams(devPath));
  });
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} padIdx
 * @param {number} chainIdx
 * @param {number} subDevIdx
 */
function lom_get_drum_pad_chain_device_params(id, track, devIdx, padIdx, chainIdx, subDevIdx) {
  _handle(id, function () {
    var devPath =
      _drumPadPath(track, devIdx, padIdx) +
      ' chains ' +
      parseInt(chainIdx) +
      ' devices ' +
      parseInt(subDevIdx);
    return JSON.stringify(_readDeviceParams(devPath));
  });
}

/**
 * Outlet JSON of a rack's macros + variation state in one call. Macros are
 * filtered by name prefix `Macro ` (parameters[0] is usually device on/off).
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_get_rack_macros(id, track, devIdx) {
  _handle(id, function () {
    var rackPath = _rackPath(track, devIdx);
    var rack = new LiveAPI(null, rackPath);
    var paramCount = parseInt(rack.getcount('parameters'));
    var macros = [];
    for (var i = 0; i < paramCount; i++) {
      var p = new LiveAPI(null, rackPath + ' parameters ' + i);
      var name = String(_unwrap(p.get('name')) || '');
      if (name.indexOf('Macro ') === 0) {
        macros.push({
          index: i,
          name: name,
          value: parseFloat(_unwrap(p.get('value'))),
          min: parseFloat(_unwrap(p.get('min'))),
          max: parseFloat(_unwrap(p.get('max'))),
        });
      }
    }
    return JSON.stringify({
      visible_macro_count: parseInt(_unwrap(rack.get('visible_macro_count'))),
      variation_count: parseInt(_unwrap(rack.get('variation_count'))),
      selected_variation_index: parseInt(_unwrap(rack.get('selected_variation_index'))),
      has_macro_mappings: Boolean(parseInt(_unwrap(rack.get('has_macro_mappings')))),
      macros: macros,
    });
  });
}

/**
 * Generic call wrapper for the simple rack/variation actions. Kept here
 * (rather than reusing lom_call) to avoid round-tripping through lom_request
 * and to keep semantics tied to a track+device addressing.
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {string} methodName
 */
function _rackCall(id, track, devIdx, methodName) {
  _handle(id, function () {
    var rack = new LiveAPI(null, _rackPath(track, devIdx));
    rack.call(methodName);
    return 'done';
  });
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_add_rack_macro(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'add_macro');
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_remove_rack_macro(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'remove_macro');
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_randomize_rack_macros(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'randomize_macros');
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_store_rack_variation(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'store_variation');
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_recall_last_used_variation(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'recall_last_used_variation');
}

/**
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 */
function lom_delete_rack_variation(id, track, devIdx) {
  _rackCall(id, track, devIdx, 'delete_selected_variation');
}

/**
 * Recall a specific variation by index. Sets selected_variation_index then
 * calls recall_selected_variation. -1 means "current selection, no change".
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} variationIdx
 */
function lom_recall_rack_variation(id, track, devIdx, variationIdx) {
  _handle(id, function () {
    var rack = new LiveAPI(null, _rackPath(track, devIdx));
    var idx = parseInt(variationIdx);
    if (idx >= 0) rack.set('selected_variation_index', idx);
    rack.call('recall_selected_variation');
    return 'done';
  });
}

/**
 * Insert a new (empty) chain in a regular Rack at the given position
 * (Live 12.3+). Throws if insertion is impossible (Drum Rack restrictions etc).
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} position - Negative or NaN means "at end".
 */
function lom_insert_rack_chain(id, track, devIdx, position) {
  _handle(id, function () {
    var rack = new LiveAPI(null, _rackPath(track, devIdx));
    var pos = parseInt(position);
    if (pos < 0 || isNaN(pos)) rack.call('insert_chain');
    else rack.call('insert_chain', pos);
    return 'done';
  });
}

/**
 * Drum Rack: copy the entire content of a pad to another pad slot.
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} sourceIdx
 * @param {number} destIdx
 */
function lom_copy_drum_pad(id, track, devIdx, sourceIdx, destIdx) {
  _handle(id, function () {
    var rack = new LiveAPI(null, _rackPath(track, devIdx));
    rack.call('copy_pad', parseInt(sourceIdx), parseInt(destIdx));
    return 'done';
  });
}

/**
 * Bundle: set in_note, out_note, choke_group on a DrumChain. -999 (or NaN)
 * skips a field. in_note = -1 means "All Notes" in the UI; choke_group = 0
 * = none.
 *
 * @param {number} id
 * @param {number} track
 * @param {number} devIdx
 * @param {number} padIdx
 * @param {number} chainIdx
 * @param {number} inNote
 * @param {number} outNote
 * @param {number} chokeGroup
 */
function lom_set_drum_chain_props(
  id,
  track,
  devIdx,
  padIdx,
  chainIdx,
  inNote,
  outNote,
  chokeGroup
) {
  _handle(id, function () {
    var c = new LiveAPI(
      null,
      _drumPadPath(track, devIdx, padIdx) + ' chains ' + parseInt(chainIdx)
    );
    var n;
    n = parseInt(inNote);
    if (!isNaN(n) && n !== -999) c.set('in_note', n);
    n = parseInt(outNote);
    if (!isNaN(n) && n !== -999) c.set('out_note', n);
    n = parseInt(chokeGroup);
    if (!isNaN(n) && n !== -999) c.set('choke_group', n);
    return 'done';
  });
}

// ━━━ from 50_observers.js ━━━

// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Push notifications via LiveAPI observers. Each observe call returns an
// observer id; the bridge outlets `lom_event obsId value` on every change
// (with throttle + trailing flush).
//
// Per-observer state. Keyed by an integer id we hand out at lom_observe time
// and the bridge can use to address the observer (lom_unobserve + matching
// lom_event back to the right URI). Each entry holds:
//   api          : the LiveAPI instance with .property = <prop> + callback
//   throttle_ms  : minimum gap between two emitted events (0 = no throttle)
//   last_emit    : timestamp of last emission
//   pending      : the most recent suppressed value waiting to be flushed
//   timer_id     : Max Task scheduling the trailing flush, null if none
var observers = {}; // id -> { api, throttle_ms, last_emit, pending, timer_id, prop }
var nextObsId = 1;

/**
 * Trailing-edge throttle: when an event arrives too fast and is suppressed,
 * we schedule a Task that flushes the most recent value once the throttle
 * window has passed. Guarantees we never lose the *final* value of a burst
 * (e.g. tempo settles at 130 after 60 frames of dragging — agent must see
 * 130, not the last value before throttle kicked in).
 *
 * @param {number} obsId
 */
function _scheduleObserverFlush(obsId) {
  var st = observers[obsId];
  if (!st || st.timer_id !== null) return;
  var delay = Math.max(0, st.throttle_ms - (Date.now() - st.last_emit));
  st.timer_id = new Task(function () {
    var s = observers[obsId];
    if (!s) return;
    s.timer_id = null;
    if (s.pending === null) return;
    s.last_emit = Date.now();
    var val = s.pending;
    s.pending = null;
    outlet(0, 'lom_event', obsId, _serializeForOutlet(val));
  });
  st.timer_id.schedule(delay);
}

/**
 * Coerce a value into something Max-outlet-friendly. Numbers / bools / strings
 * pass through ; lists and dicts are JSON-stringified so Node-side consumers
 * can decode uniformly.
 *
 * @param {unknown} val
 * @returns {string|number|boolean}
 */
function _serializeForOutlet(val) {
  if (val === undefined || val === null) return '';
  if (typeof val === 'number' || typeof val === 'boolean' || typeof val === 'string') return val;
  try {
    return JSON.stringify(val);
  } catch (e) {
    return String(val);
  }
}

/**
 * Subscribe to a LiveAPI property. Hands back an integer observer id (in the
 * `lom_response` envelope) that the bridge uses to address the observer for
 * unobserve and to route incoming `lom_event obsId value` notifications.
 *
 * @param {number} id
 * @param {string} lomPath
 * @param {string} prop
 * @param {number} throttleMs - 0 = no throttle.
 */
function lom_observe(id, lomPath, prop, throttleMs) {
  _handle(id, function () {
    var path = String(lomPath);
    var propName = String(prop);
    var throttle = Math.max(0, parseInt(throttleMs) || 0);
    var obsId = nextObsId++;

    var handler = function (args) {
      // args = [<prop_name>, value_or_values_flat]. Single-atom case keeps a
      // scalar ; multi-atom (dict-typed props returning key/value pairs)
      // forwards the original structure.
      var st = observers[obsId];
      if (!st) return; // stale callback after free
      var raw = args.slice(1);
      var val = raw.length === 1 ? raw[0] : raw;

      var now = Date.now();
      if (throttle === 0 || now - st.last_emit >= throttle) {
        st.last_emit = now;
        st.pending = null;
        outlet(0, 'lom_event', obsId, _serializeForOutlet(val));
      } else {
        // Suppressed by throttle — remember the latest value and schedule a
        // trailing flush so the final value of a burst is never lost.
        st.pending = val;
        _scheduleObserverFlush(obsId);
      }
    };

    var api = new LiveAPI(handler, path);
    api.property = propName;

    observers[obsId] = {
      api: api,
      throttle_ms: throttle,
      last_emit: 0,
      pending: null,
      timer_id: null,
      prop: propName,
    };

    return obsId;
  });
}

/**
 * Stop a previously-registered observer. Idempotent: unobserving an
 * already-freed observer outlets `ok already-freed`.
 *
 * @param {number} id
 * @param {number} observerId
 */
function lom_unobserve(id, observerId) {
  _handle(id, function () {
    var obsId = parseInt(observerId);
    var st = observers[obsId];
    if (!st) return 'already-freed';
    if (st.timer_id) {
      try {
        st.timer_id.cancel();
      } catch (_) {}
    }
    /* istanbul ignore else -- defensive: lom_observe always populates api */
    if (st.api) {
      try {
        st.api.property = '';
      } catch (_) {}
      try {
        st.api = null;
      } catch (_) {}
    }
    delete observers[obsId];
    return 'done';
  });
}

// ━━━ from 60_routing.js ━━━

// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Track input / output routing (type + channel).

/**
 * Set a Track's routing dict prop (input_routing_type / output_routing_type
 * / input_routing_channel / output_routing_channel). The set call expects a
 * Dict whose identifier matches one in the corresponding available_<prop>s
 * list — we validate first to fail loudly on bad identifiers AND to preserve
 * the native identifier type (Live 12 uses ints for some channels, symbols
 * for others; the Dict round-trip must keep the original type).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {string} propName - One of the four routing prop names above.
 * @param {string} identifier
 */
function lom_set_track_routing(id, trackIndex, propName, identifier) {
  _handle(id, function () {
    var track = new LiveAPI(null, _trackPath(trackIndex));

    var prop = String(propName);
    var availName = 'available_' + prop + 's';
    var rawAvail = track.get(availName);
    var availStr = Array.isArray(rawAvail) && rawAvail.length === 1 ? rawAvail[0] : rawAvail;

    var avail = [];
    if (typeof availStr === 'string' && availStr.charAt(0) === '{') {
      try {
        var parsed = JSON.parse(availStr);
        avail = parsed[availName] || [];
      } catch (_) {}
    }

    var idStr = String(identifier);
    var match = null;
    for (var i = 0; i < avail.length; i++) {
      if (String(avail[i].identifier) === idStr) {
        match = avail[i];
        break;
      }
    }
    if (!match) {
      var have = [];
      for (var j = 0; j < avail.length; j++) {
        have.push(JSON.stringify(avail[j].identifier) + ' (' + avail[j].display_name + ')');
      }
      throw new Error(
        'No ' + prop + ' with identifier "' + idStr + '". Available: ' + have.join(', ')
      );
    }

    var d = new Dict();
    d.parse(JSON.stringify(match));
    track.set(prop, d);

    return JSON.stringify(match);
  });
}

/**
 * Read input_routing_{type,channel} or output_routing_{type,channel} on a
 * track plus their available_* lists. Outlet JSON
 *   { type: {current, available}, channel: {current, available} }.
 *
 * Live 12+ returns dict-typed properties as a JSON-string envelope ; older
 * versions returned alternating key/value lists (kept as fallback).
 *
 * @param {number} id
 * @param {number} trackIndex
 * @param {string} side - 'input' or 'output'.
 */
function lom_get_track_routing(id, trackIndex, side) {
  _handle(id, function () {
    var track = new LiveAPI(null, _trackPath(trackIndex));
    var prefix = String(side);

    /**
     * @param {string} propName
     * @returns {unknown}
     */
    function readProp(propName) {
      var raw = track.get(propName);
      var val = Array.isArray(raw) && raw.length === 1 ? raw[0] : raw;
      if (typeof val === 'string' && val.charAt(0) === '{') {
        try {
          var parsed = JSON.parse(val);
          return parsed[propName] !== undefined ? parsed[propName] : parsed;
        } catch (_) {}
      }
      if (Array.isArray(val)) {
        var o = {};
        for (var i = 0; i < val.length; i += 2) o[val[i]] = val[i + 1];
        return o;
      }
      return val;
    }

    return JSON.stringify({
      type: {
        current: readProp(prefix + '_routing_type'),
        available: readProp('available_' + prefix + '_routing_types'),
      },
      channel: {
        current: readProp(prefix + '_routing_channel'),
        available: readProp('available_' + prefix + '_routing_channels'),
      },
    });
  });
}

// ━━━ from 70_session.js ━━━

// AUTO-AUTHORED — this file is one of several concatenated at build
// time into the single app/lom_router.js that Max [js] loads. Edit
// individual files in app/lom_router/ ; the concatenated output is
// regenerated by `node tools/build/concat-lom.js`.

// Session-level reads & selection: cue points, scenes, grooves,
// take lanes, group info, scale, control surfaces, current selection.

/**
 * Set the name of a cue point (resolved by index in Song.cue_points).
 *
 * @param {number} id
 * @param {number} cueIndex
 * @param {string} name
 */
function lom_set_cue_point_name(id, cueIndex, name) {
  _handle(id, function () {
    var cp = _byId(_resolveCueId(cueIndex));
    if (!cp) throw new Error('No cue point at index ' + cueIndex);
    cp.set('name', String(name));
    return 'done';
  });
}

/**
 * Set the time (beat position) of a cue point.
 *
 * @param {number} id
 * @param {number} cueIndex
 * @param {number} time
 */
function lom_set_cue_point_time(id, cueIndex, time) {
  _handle(id, function () {
    var cp = _byId(_resolveCueId(cueIndex));
    if (!cp) throw new Error('No cue point at index ' + cueIndex);
    cp.set('time', parseFloat(time));
    return 'done';
  });
}

/**
 * Jump the playhead to a cue point.
 *
 * @param {number} id
 * @param {number} cueIndex
 */
function lom_jump_to_cue(id, cueIndex) {
  _handle(id, function () {
    var cp = _byId(_resolveCueId(cueIndex));
    if (!cp) throw new Error('No cue point at index ' + cueIndex);
    cp.call('jump');
    return 'done';
  });
}

/**
 * Iterate Song.cue_points and outlet JSON `[{name, time}, ...]`.
 *
 * @param {number} id
 */
function lom_get_cue_points(id) {
  _handle(id, function () {
    var song = new LiveAPI(null, 'live_set');
    var out = [];
    _foreachChild(song, 'cue_points', function (cp) {
      out.push({
        name: String(_unwrap(cp.get('name'))),
        time: parseFloat(_unwrap(cp.get('time'))),
      });
    });
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON of all grooves in the groove pool. base is an int enum:
 * 0=1/4, 1=1/8, 2=1/8T, 3=1/16, 4=1/16T, 5=1/32.
 *
 * @param {number} id
 */
function lom_get_grooves(id) {
  _handle(id, function () {
    var pool = new LiveAPI(null, 'live_set groove_pool');
    var count = parseInt(pool.getcount('grooves'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var g = new LiveAPI(null, 'live_set groove_pool grooves ' + i);
      out.push({
        index: i,
        name: String(_unwrap(g.get('name')) || ''),
        base: parseInt(_unwrap(g.get('base'))),
        quantization_amount: parseFloat(_unwrap(g.get('quantization_amount'))),
        random_amount: parseFloat(_unwrap(g.get('random_amount'))),
        timing_amount: parseFloat(_unwrap(g.get('timing_amount'))),
        velocity_amount: parseFloat(_unwrap(g.get('velocity_amount'))),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON `[{index, name}, ...]` for take lanes of a track. TakeLane has
 * only a 'name' property and arrangement_clips child — name is the most
 * useful per-lane identifier.
 *
 * @param {number} id
 * @param {number} trackIndex
 */
function lom_get_take_lanes(id, trackIndex) {
  _handle(id, function () {
    var trackPath = _trackPath(trackIndex);
    var t = new LiveAPI(null, trackPath);
    var count = parseInt(t.getcount('take_lanes'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var lane = new LiveAPI(null, trackPath + ' take_lanes ' + i);
      out.push({
        index: i,
        name: String(_unwrap(lane.get('name')) || ''),
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON of the current Song.View selection state:
 *   { selected_track_index, selected_scene_index, highlighted_clip_slot,
 *     detail_clip_path, selected_device_path, selected_chain_path }.
 * `_path` fields are LOM canonical paths or null.
 *
 * @param {number} id
 */
function lom_get_selection(id) {
  _handle(id, function () {
    var view = new LiveAPI(null, 'live_set view');
    /**
     * @param {Array} childRef
     * @returns {string|null}
     */
    function pathOf(childRef) {
      if (Array.isArray(childRef) && childRef.length >= 2 && childRef[0] === 'id') {
        var api = _byId(childRef[1]);
        if (!api) return null;
        return String(api.path || '').replace(/^"|"$/g, '') || null;
      }
      return null;
    }
    /**
     * @param {string|null} path
     * @param {string} kind
     * @returns {number}
     */
    function indexFromPath(path, kind) {
      if (!path) return -1;
      var re = new RegExp('live_set ' + kind + ' (\\d+)');
      var m = path.match(re);
      return m ? parseInt(m[1]) : -1;
    }
    var hcsPath = pathOf(view.get('highlighted_clip_slot'));
    var hcs = null;
    if (hcsPath) {
      var hm = hcsPath.match(/live_set tracks (\d+) clip_slots (\d+)/);
      if (hm) hcs = { track: parseInt(hm[1]), slot: parseInt(hm[2]) };
    }
    return JSON.stringify({
      selected_track_index: indexFromPath(pathOf(view.get('selected_track')), 'tracks'),
      selected_scene_index: indexFromPath(pathOf(view.get('selected_scene')), 'scenes'),
      highlighted_clip_slot: hcs,
      detail_clip_path: pathOf(view.get('detail_clip')),
      selected_device_path: pathOf(view.get('selected_parameter')),
      selected_chain_path: pathOf(view.get('selected_chain')),
    });
  });
}

/**
 * Select a track in Live's UI (Song.View.selected_track). Setting a
 * child-ref prop in jsliveapi takes the form view.set(prop, 'id', N).
 *
 * @param {number} id
 * @param {number} trackIndex
 */
function lom_select_track(id, trackIndex) {
  _handle(id, function () {
    var t = new LiveAPI(null, _trackPath(trackIndex));
    var tid = t.id;
    if (!tid || tid === 0 || tid === '0') throw new Error('No track at index ' + trackIndex);
    var view = new LiveAPI(null, 'live_set view');
    view.set('selected_track', 'id', tid);
    return 'done';
  });
}

/**
 * Select a scene in Live's UI.
 *
 * @param {number} id
 * @param {number} sceneIndex
 */
function lom_select_scene(id, sceneIndex) {
  _handle(id, function () {
    var s = new LiveAPI(null, 'live_set scenes ' + parseInt(sceneIndex));
    var sid = s.id;
    if (!sid || sid === 0 || sid === '0') throw new Error('No scene at index ' + sceneIndex);
    var view = new LiveAPI(null, 'live_set view');
    view.set('selected_scene', 'id', sid);
    return 'done';
  });
}

/**
 * Track group info bundle: {is_foldable, is_grouped, fold_state,
 * group_track_index} in one round-trip. group_track_index is -1 for
 * top-level tracks; otherwise we follow Track.group_track and parse its
 * canonical path to extract the parent's index.
 *
 * @param {number} id
 * @param {number} trackIndex
 */
function lom_get_track_group_info(id, trackIndex) {
  _handle(id, function () {
    var t = new LiveAPI(null, _trackPath(trackIndex));
    var info = {
      is_foldable: Boolean(parseInt(_unwrap(t.get('is_foldable')))),
      is_grouped: Boolean(parseInt(_unwrap(t.get('is_grouped')))),
      fold_state: parseInt(_unwrap(t.get('fold_state'))),
      group_track_index: -1,
    };
    if (info.is_grouped) {
      var gt = t.get('group_track');
      var gtId = Array.isArray(gt) && gt.length >= 2 && gt[0] === 'id' ? gt[1] : 0;
      var gtApi = _byId(gtId);
      if (gtApi) {
        var gtPath = String(gtApi.path || '').replace(/^"|"$/g, '');
        var matched = gtPath.match(/live_set tracks (\d+)/);
        if (matched) info.group_track_index = parseInt(matched[1]);
      }
    }
    return JSON.stringify(info);
  });
}

/**
 * Read all scale-related props in one round-trip (Live 12+). scale_intervals
 * may come back as a JSON-string envelope or a flat array depending on Live
 * version.
 *
 * @param {number} id
 */
function lom_get_scale(id) {
  _handle(id, function () {
    var s = new LiveAPI(null, 'live_set');
    var rawIntervals = s.get('scale_intervals');
    var intervals;
    var ival =
      Array.isArray(rawIntervals) && rawIntervals.length === 1 ? rawIntervals[0] : rawIntervals;
    if (typeof ival === 'string' && ival.charAt(0) === '{') {
      try {
        var parsed = JSON.parse(ival);
        intervals = parsed.scale_intervals !== undefined ? parsed.scale_intervals : parsed;
      } catch (_) {
        intervals = [];
      }
    } else if (Array.isArray(rawIntervals)) {
      intervals = rawIntervals.slice();
    } else {
      intervals = [];
    }
    return JSON.stringify({
      scale_name: String(_unwrap(s.get('scale_name')) || ''),
      root_note: parseInt(_unwrap(s.get('root_note'))),
      scale_mode: Boolean(parseInt(_unwrap(s.get('scale_mode')))),
      scale_intervals: intervals,
    });
  });
}

/**
 * Outlet JSON `[{index, type_name, is_connected}, ...]` for the active
 * control surfaces (hardware controllers mapped in Tempo & MIDI Preferences).
 * Empty slots have type_name = 'None' or empty.
 *
 * @param {number} id
 */
function lom_get_control_surfaces(id) {
  _handle(id, function () {
    var app = new LiveAPI();
    app.path = 'live_app';
    var count = parseInt(app.getcount('control_surfaces'));
    var out = [];
    for (var i = 0; i < count; i++) {
      var cs = new LiveAPI(null, 'control_surfaces ' + i);
      var typeName = String(_unwrap(cs.get('type_name')) || '');
      out.push({
        index: i,
        type_name: typeName || 'None',
        is_connected: typeName !== '' && typeName !== 'None' && typeName !== '0',
      });
    }
    return JSON.stringify(out);
  });
}

/**
 * Outlet JSON list of control names (buttons/knobs/pads) exposed by a given
 * control surface.
 *
 * @param {number} id
 * @param {number} surfaceIndex
 */
function lom_get_control_surface_controls(id, surfaceIndex) {
  _handle(id, function () {
    var cs = new LiveAPI(null, 'control_surfaces ' + parseInt(surfaceIndex));
    var raw = cs.get('control_names');
    var names = Array.isArray(raw) ? raw : raw ? [raw] : [];
    return JSON.stringify(
      names.map(function (n) {
        return String(n);
      })
    );
  });
}
